### ISSUE TITLE
NTR: mobile RNA, mobile polypeptide

### ISSUE THREAD

**Issue by tberardini** [The-Sequence-Ontology/SO-Ontologies#333]
Question:
mobile(SO:0001234)
An attribute describing a feature that has either intra-genome or intracellular mobility.

Can the mobility attribute be extended to intra-organismal mobility?  I would like to annotate proteins and RNAs that move within an organism, specifically within a plant, for example from root to shoot through the symplast.

If yes, then the following new SO terms are requested:

mobile RNA: RNA has_quality mobile
mobile polypeptide: polypeptide has_quality mobile
syn: mobile protein

**Comment by tberardini** [comment]
@cmungall @keilbeck

**Comment by keilbeck** [comment]
Hi Tanya,
I think that the meaning of mobile in the sequence sense is different from mobile in the sense of molecules that migrate across tissues. I think your case needs more specific definition, as lots of proteins/RNAs move to one degree or another either within a cell or forming a gradient in a tissue etc. Could you define the two terms without the doing the crossproduct and could we change it to migratory instead of mobile?

**Comment by tberardini** [comment]
Hmmm, maybe SO is not the best place then for this class.  I'll look into using the PATO:mobile instead.  Maybe we can capture the protein/RNA mobility as a phenotype annotation.

mobile(PATO:0000299)
A mobility quality of inhering in a bearer by virtue of the bearer's disposition to move freely.

**Comment by keilbeck** [comment]
That honestly sounds truer to me. I hate losing a good term to pato, but in this case I think it works better.

**Comment by tberardini** [comment]
Thanks for your feedback, Karen.  Going to close this.
