### ISSUE TITLE
Is there an appropriate term for reference allele?

### ISSUE THREAD

**Issue by dandanxu** [The-Sequence-Ontology/SO-Ontologies#334]
For when the sequenced allele is not different from the reference genome. See
<img width="926" alt="screen shot 2015-10-13 at 12 58 59" src="https://cloud.githubusercontent.com/assets/4357327/10462028/53a43cf0-71aa-11e5-8057-6082e68e8a00.png">.
We currently have an effect predictor that outputs everything in sequence ontology terms, but right now, if the variant is the reference allele at the locus, we don't have a good way of displaying that "predicted effect" or term for this.

**Comment by srynobio** [comment]
In our collaborations with [ClinGen](https://www.clinicalgenome.org/) we are currently working on adding a term to SO to handle this very thing.

The term being considered is:
```
id: no_sequence_alteration
``` 
Currently we are working on the final definition, but it would specify a sequence location where the observed allele matches the reference.

Any additional input from the community would be welcome.

**Comment by thefferon** [comment]
NCBI had the following exchange with SO in January 2014:

4. With the emergence of personal genomes it is increasingly important to represent not only where a person's genome deviates from the reference, but to be explicit when a locus has been typed and specifically does NOT deviate from the reference. This should be reported as positive data (rather than remain unreported because it does not differ from the reference).

Request: Please add the term 'no_variation' to the SO:

term: no_variation
definition: a sequence at a defined location that is defined to match the reference assembly
synonyms: reference match
parent: sequence_alteration
This one is difficult to place in the ontology for obvious reasons - it is not an alteration. There has not previously been a use case for this as a variant file would not contain it.
Can you explain more about your use case for this?
The only solution to fit this into the ontology would be to have a parent class of sequence alteration and have the new term be a sibling of alteration.
I don't know what the super class would be.
We definitely need to talk thru this one…

I don’t believe it was ever followed up on or resolved.




On Oct 13, 2015, at 3:10 PM, Shawn Rynearson <notifications@github.com<mailto:notifications@github.com>> wrote:


In our collaborations with ClinGen<https://www.clinicalgenome.org/> we are currently working on adding a term to SO to handle this very thing.

The term being considered is:

id: no_sequence_alteration


Currently we are working on the final definition, but it would specify a sequence location where the observed allele matches the reference.

Any additional input from the community would be welcome.

**Comment by thefferon** [comment]
– The fault likely being mine.

On Oct 13, 2015, at 3:20 PM, Tim Hefferon <theffero@ncbi.nlm.nih.gov<mailto:theffero@ncbi.nlm.nih.gov>> wrote:

NCBI had the following exchange with SO in January 2014:

4. With the emergence of personal genomes it is increasingly important to represent not only where a person's genome deviates from the reference, but to be explicit when a locus has been typed and specifically does NOT deviate from the reference. This should be reported as positive data (rather than remain unreported because it does not differ from the reference).

Request: Please add the term 'no_variation' to the SO:

term: no_variation
definition: a sequence at a defined location that is defined to match the reference assembly
synonyms: reference match
parent: sequence_alteration
This one is difficult to place in the ontology for obvious reasons - it is not an alteration. There has not previously been a use case for this as a variant file would not contain it.
Can you explain more about your use case for this?
The only solution to fit this into the ontology would be to have a parent class of sequence alteration and have the new term be a sibling of alteration.
I don't know what the super class would be.
We definitely need to talk thru this one…

I don’t believe it was ever followed up on or resolved.




On Oct 13, 2015, at 3:10 PM, Shawn Rynearson <notifications@github.com<mailto:notifications@github.com>> wrote:


In our collaborations with ClinGen<https://www.clinicalgenome.org/> we are currently working on adding a term to SO to handle this very thing.

The term being considered is:

id: no_sequence_alteration


Currently we are working on the final definition, but it would specify a sequence location where the observed allele matches the reference.

Any additional input from the community would be welcome.

**Comment by dandanxu** [comment]
@srynobio Great! We would be delighted to see something like `no_sequence_alteration`. Any ideas on when this might be implemented?
Also, is there an open list/discussion somewhere on SO terms the Clingen/SO collaboration are planning on defining? We (at SolveBio) have been actively developing our variant-specific algorithms around SO terms and it'd be great to be able to know what's coming up.

**Comment by srynobio** [comment]
Coincidence, your solvebio webpage was just brought up today with one of our ClinGen calls, it look interesting.

As far as an open list/discussion we currently do not have one to my knowledge, the term `no_sequence_alteration` is being added to aid our [Data Model](http://datamodel.clinicalgenome.org/development/allele/implementation/value_set_list/) efforts.  

However, ideas for term and improvements can always be submitted via github issue.

**Comment by dandanxu** [comment]
Oh how random! Let me know if you want a walkthrough anytime, we're always open to feedback and collaborations: dandan@solvebio.com. We will definitely submit issues/ideas for SO as we come across them.

**Comment by keilbeck** [comment]
We settled on this term
no_variation SO:0002073
a sibling of sequence_alteration and a child of sequence_comparison

**Comment by thefferon** [comment]
Hi Karen,

NCBI inquired a while back about requesting an SO term for “no variation” – i.e., an assertion that an allele was probed and found to NOT be different from the reference.

Is no_variation SO:0002073 the answer to this? When was it / will it be added? I don’t find it in the current release or SVN in the SO Browser -

Thanks,
Tim



On Mar 7, 2016, at 12:32 PM, Karen EIlbeck <notifications@github.com<mailto:notifications@github.com>> wrote:


We settled on this term
no_variation SO:0002073
a sibling of sequence_alteration and a child of sequence_comparison

**Comment by keilbeck** [comment]
It was added in the fall.
It should be there.
I am going to save a revision today and make a release.
—K

Karen Eilbeck
Associate Professor
Biomedical Informatics
University of Utah

**Comment by dandanxu** [comment]
Does the sequence ontology website (http://www.sequenceontology.org/browser/obob.cgi) tend to be updated much later than the .obo files? I see the no_variation in the .obo files, but its not on the MISO web pages (which we mostly work off).

**Comment by keilbeck** [comment]
I think there must be a glitch somewhere. I will look into it. You are the second person today to comment about that.

--K

**Comment by thefferon** [comment]
Hi Karen,

Any progress on this? I still don't see 'no_variation SO:0002073' in the Miso browser. ("I don't see no variation???")

NCBI requests an update to this term's definition, please.

Current definition:
"No_variation is a position or feature within a sequence, when compared to a reference  sequence, that does not display any variation."

Proposed definitions (please comment on which is preferable):

**1.** "a position or feature within a sequence that is identical to the comparable position or feature of a specified reference sequence"

**2.** "a locus on a sequence that is identical to the comparable locus on a specified reference sequence"

–Tim

**Comment by keilbeck** [comment]
We need to alter the spec to be the  parent of sequence alteration

Karen Eilbeck
Associate Professor
Biomedical Informatics
University of Utah

**Comment by thefferon** [comment]
@keilbeck , Any comment on the proposed values for redefining SO:0002073?
Thanks

**Comment by keilbeck** [comment]
Hi TIm
I can update the definition to the 1st one you gave:
 "a position or feature within a sequence that is identical to the comparable position or feature of a specified reference sequence"

Does that work for you still?

Shawn is working on getting miSO to work with git.

**Comment by thefferon** [comment]
Hi Karen,
Great! Thanks for the follow-up.
Is there a ticket for updating the GVF spec to "parent of sequence_alteration"? Should I open one?
Thanks,
Tim

**Comment by keilbeck** [comment]
Please open one.  That would be great.

**Comment by thefferon** [comment]
@keilbeck – OK! Is there a separate github section for GVF, or shall I open a ticket in SO-Ontologies?

**Comment by keilbeck** [comment]
Put it in SO for now.
THanks

**Comment by thefferon** [comment]
@dandanxu, @srynobio:  Are there any persisting incompatibilities (especially w.r.t. ClinGen-related workflows) between the term SO:0002073 (no_variation) and the term discussed above (no_sequence_alteration)? If there is a compelling need for the term to be no_sequence_alteration, and if @keilbeck agrees to the possibility of a change, I can find out if NCBI would have any problems updating the term name. OR - could it be listed as an alias?

**Comment by keilbeck** [comment]
Hi all

I have moved sequence comparison to be the parent of sequence alteration.
I have renamed no_variation to be no_sequence_alteration
It is a sibling of sequence_alteration. I updated the definition: A position or feature within a sequence that is identical to the comparable position or feature of a specified reference sequence.

Tim, do you need to go in and update the spec?

Does this fix your immediate issues?
--K

**Comment by keilbeck** [comment]
It is checked in now Tim, look for the latest revision.

**Comment by dandanxu** [comment]
@thefferon my apologies didn't see this thread till now. we have no problem with `no_sequence_alteration`. looking forward to seeing it on MISO (is it a new SO id or still SO:0002073?).

**Comment by srynobio** [comment]
I have no issue as well, originally `no_sequence_alteration` was the term I prefered, I also prefer the new placement within the ontology.

**Comment by thefferon** [comment]
@dandanxu ,

> is it a new SO id or still SO:0002073?

SO:0002073: **no_sequence_alteration**
is a sibling of
SO:0001059: **sequence_alteration**
both the above are children of
SO:0002072: **sequence_comparison**
which is a child of
SO:0000110: **sequence_feature**
