### ISSUE TITLE
VNTR should not be an exact synonym to microsatellite

### ISSUE THREAD

**Issue by maglott** [The-Sequence-Ontology/SO-Ontologies#352]
The current definition of microsatellite 
 	A repeat_region containing repeat_units of 2 to 10 bp repeated in tandem.

VNTRs should be minisatellite , because the term is usually used for repeats longer than in the micro category

**Comment by thefferon** [comment]
Some useful links on repeat definitions (not that MeSH is the authoritative source for this info):

### [Minisatellite Repeats](https://www.nlm.nih.gov/cgi/mesh/2011/MB_cgi?mode=&term=Variable+Number+of+Tandem+Repeats)
**Synonyms:** Minisatellites, Simple Repetitive Sequence, Variable Number of Tandem Repeats, Variable Tandem Repeats, VNTR, VNTR Loci, VNTR Region, VNTR Sequences
**Note:** Tandem arrays of moderately repetitive (5-50 repeats) short (10-60 bases) DNA sequences found dispersed throughout the genome and clustered near telomeres. Their degree of repetition is two to several hundred at each locus. Loci number in the thousands but each locus shows a distinctive repeat unit. Minisatellite repeats are often called variable number of tandem repeats.
### [Microsatellite Repeats](https://www.nlm.nih.gov/cgi/mesh/2011/MB_cgi?mode=&term=Microsatellite+Repeats&field=entry#TreeG02.111.570.080.708.800.500)
**Synonyms:** Microsatellite Markers, Microsatellites, Pentanucleotide Repeats, Short Tandem Repeats, Tetranucleotide Repeats
**Note:** A variety of simple di- ( DINUCLEOTIDE REPEATS), tri- ( TRINUCLEOTIDE REPEATS), tetra-, and pentanucleotide tandem repeats (usually less than 100 bases long). They are dispersed in the euchromatic arms of most chromosomes. They are also known as short tandem repeats (STRs).
### [DNA, Satellite](https://www.nlm.nih.gov/cgi/mesh/2011/MB_cgi?mode=&term=DNA,+Satellite&field=entry#TreeG05.360.080.708.800.150)
**Synonyms:** Satellite DNA, Satellite I DNA
**Note:** Highly repetitive DNA sequences found in HETEROCHROMATIN, mainly near centromeres. They are composed of simple sequences (very short) (see MINISATELLITE REPEATS) repeated in tandem many times to form large blocks of sequence. Additionally, following the accumulation of mutations, these blocks of repeats have been repeated in tandem themselves. The degree of repetition is on the order of 1000 to 10 million at each locus. Loci are few, usually one or two per chromosome. They were called satellites since in density gradients, they often sediment as distinct, satellite bands separate from the bulk of genomic DNA owing to a distinct BASE COMPOSITION.

**Comment by nicoleruiz** [comment]
Thank you for bringing this to our attention and for the references.

I removed VNTR as a synonym of microsatellite and made it an exact synonym of minisatellite. I added STR as an exact synonym of microsatellite.

The SO browser is not showing these changes yet, but it should update soon. Let me know if there are any other concerns.

**Comment by srynobio** [comment]
The SO Browser should not be up to date.
