### ISSUE TITLE
SO term for H2A.Zac

### ISSUE THREAD

**Issue by makostadima** [The-Sequence-Ontology/SO-Ontologies#369]
Hello,

Could you please a new sequence ontology term for H2A.Zac under http://www.sequenceontology.org/browser/current_svn/term/SO:0001702

Thank you,
Myrto Kostadima

**Comment by nicoleruiz** [comment]
Term: H2A.Z_acetylation_site
Definition: A kind of histone modification site, whereby the lysines K4, K7 and K11, from the start of the H2A.Z histone protein is acetylated.
synonym: H2A.Zac EXACT
synonym: H2A.Z acetylation site EXACT
synonym: acH2A.Z EXACT
is_a: SO:0001702 ! histone_acetylation_site

References:
http://www.ncbi.nlm.nih.gov/pubmed/27087541
http://www.ncbi.nlm.nih.gov/pubmed/24316985
http://www.ncbi.nlm.nih.gov/pubmed/19385636

I'm not sure about what specific lysines are acetylated. Some of the papers I referenced named other lysines (K13, K15)  that were also acetylated but at lower frequencies. The most recent publication listed K4, K7 and K11 so that is what I used for the definition. Please make any changes to the proposed term.

**Comment by theintuitivesoul** [comment]
I will try, I don't want to mess anything else up again. I am still not
sure how to sort whether this belongs to me or my husband.

**Comment by makostadima** [comment]
Looking at this article (https://www.ncbi.nlm.nih.gov/pubmed/24316985), I would also add K13 and K15.

Otherwise looks good.

**Comment by nicoleruiz** [comment]
@keilbeck I've gone back and looked at the way the other histone acetylation sites are documented in the ontology. Each lysine that is acetylated for a particular histone has its own term. Should this H2A histone variant have terms for each lysine that is acetylated or should there be a generic H2A.Z acetylation site term with all of the individual terms for each lysine as child terms?

**Comment by nicoleruiz** [comment]
I had to make some changes to the term I originally proposed because of the way histone acetylation terms are organized in SO. I also had to rearrange some of the existing histone acetylation terms. 

I ended up making the term histone_2AZ_acetylation_site (SO:0002144) which is a histone 2AZ modification where the modification is the acetylation of the residue. I then created child terms for each lysine that is acetylated. For example, the term H2AZK4_acetylation_site (SO:0002145) is for the 4th lysine of H2AZ that is acetylated. I created terms for lysines 4, 7, 11, 13 and 15.

**Comment by makostadima** [comment]
Have you pushed this to the live site too? I just can't seem to find it.

**Comment by nicoleruiz** [comment]
I have pushed the changes to github. It will take a few days for the changes to show when using the Sequence Ontology browser.

**Comment by nicoleruiz** [comment]
The changes are showing on the site.
