### ISSUE TITLE
Wrong IRIs for ObjectProperties in so.owl

### ISSUE THREAD

**Issue by mcourtot** [The-Sequence-Ontology/SO-Ontologies#380]
Hi,

Looking at http://purl.obolibrary.org/obo/so.owl, the header defines

```
xmlns:obo="http://purl.obolibrary.org/obo/"
xmlns:so-xp="http://purl.obolibrary.org/obo/so-xp.obo#"
```

While the SO classes seem ok (e.g., http://purl.obolibrary.org/obo/SO_0000041), the object properties use the wrong namespaces, e.g. http://purl.obolibrary.org/obo/so-xp.obo#contained_by

cc @cmungall

**Comment by davidwsant** [comment]
Hi @mcourtot,

I apologize that this issue has been left since 2016. We had a change in staff. 

We realized that our pipeline had not been updating the cross-product terms since this GitHub repository was created in 2015. We have since moved the xp files to the Legacy folder and the xp line referenced above is no longer in the owl files. I believe the problems have been resolved. You are welcome to check the current files in this repository. If other issues are found, please re-open the issue and comment on the problems found or create a new issue request.

Thank you,

Dave Sant
