### ISSUE TITLE
Need to distinguish sequence alterations that are due to assembly from those that are biological

### ISSUE THREAD

**Issue by selewis** [The-Sequence-Ontology/SO-Ontologies#388]
Hi there,

In the Apollo genome editor we have added the capability for curators to indicate sequence alterations (i.e. substitutions, deletions, and insertions). They have the option of indicating whether the source of the alteration is due to a genuine biological difference, or the source of the alteration is due to an artifact in the base-calling/assembly process. For the first we can use the existing SO types, however, but for the second we have a problem because substitution, deletion, and insertion are all child classes of biological region. What we need are equivalent distinctions (child classes) under base_call_error_correction and/or perhaps assembly_error_correction. It's more likely the former, but it may be possible that the error could arise from the assembly. (so another question is what would be the correct parent class if this isn't known).

Help please!

nota bene 1: In Apollo all features are typed using SO
nota bene 2: We're using the dbSNP definition of SNP which is alterations <=50bp "dbSNP does not accept synthetic mutations or variations ascertained from cross-species alignments and analysis. Variations > 50 nucleotides in length should be submitted to the Database of Genomic Structural Variation (dbVAR)" https://www.ncbi.nlm.nih.gov/books/NBK174586/

**Comment by nicoleruiz** [comment]
These are the changes we propose (terms in red are the new terms we would create):
![sequence_alt_artefact_fig](https://cloud.githubusercontent.com/assets/17603360/22657856/327492c4-ec55-11e6-8d36-31c96ab7130d.jpg)
Term: sequence_alteration_artefact
Definition: A sequence_alteration where the source of the alteration is due to an artefact in the base-calling or assembly process.
synonym: sequence alteration artefact
is_a: SO:0000413 ! sequence_difference

Term: indel_artefact
Definition: An indel that is the result of base-calling or assembly error.
synonym: indel artefact
is_a: sequence_alteration_artefact

Term: deletion_artefact
Definition: A deletion that is the result of base-calling or assembly error.
synonym: deletion artefact
is_a: sequence_alteration_artefact

Term: insertion_artefact
Definition: An insertion that is the result of base-calling or assembly error.
synonym: insertion artefact
is_a: sequence_alteration_artefact

Term: duplication_artefact
Definition: A duplication that is the result of base-calling or assembly error.
Synonym: duplication artefact
is_a: insertion_artefact

Term: substitution_artefact
Definition: A substitution that is the result of base-calling or assembly error.
synonym: substitution artefact
is_a: sequence_alteration_artefact

Term: SNV_artefact
Definition: An SNV that is the result of base-calling or assembly error.
synonym: SNV artefact
is_a: substitution_artefact

Term: MNV_artefact
Definition: An MNV that is the result of base-calling or assembly error.
synonym: MNV artefact
is_a: substitution_artefact

We felt that it would make sense to make sequence_alteration_artefact a child of sequence_difference since a sequence alteration could be annotated as a sequence_alteration_artefact due to a possible_base_call_error or possible_assembly_error. In addition to terms for substitution, deletion, insertion and indel artefacts, we also proposed more specific terms like SNV and MNV artefact. Are these useful? Do you need more specific terms like these for all types of sequence alterations? Please make any suggestions about what we have proposed.

**Comment by murphyte** [comment]
I believe those terms are supposed to use "artifact" (US spelling, which I see is preferred according to Karen's 2005 Genome Biology paper). I'm sure "artifact" looks just as wrong to use as "artefact" does to me ;).

-Terence

**Comment by nicoleruiz** [comment]
If there are no objections to the changes I proposed I will add these in.

**Comment by monicacecilia** [comment]
Hello, just sticking my head in here for an update. :bowtie: 
Dear @nicoleruiz have these changes been incorporated?

Adding @nathandunn: follow this ticket to inform [this one from the Apollo tracker](https://github.com/GMOD/Apollo/issues/987).

**Comment by nicoleruiz** [comment]
These changes have not been added yet. I can add these in today if you think the terms, definitions and placement in the ontology make sense. Please let me know if there are any additional terms needed.

**Comment by monicacecilia** [comment]
Hi @nicoleruiz, these terms do clarify the situation we encountered and will be tremendously useful. I agree with terms, definitions, and placement. I don't see the need for additional terms right now. Thank you!

In the future, I suppose, it will also be useful to establish the parallel between the placement for these and the sequence_feature/sequence_comparison/sequence_alteration classes. 

FYI: @nathandunn @deepakunni3 @selewis - you all will be looking at these closely when updating and correcting the editing logic to include variant viz. & annotation for the [Apollo issue I referenced earlier](https://github.com/GMOD/Apollo/issues/987).

**Comment by monicacecilia** [comment]
Eek! One more thing from me: @nicoleruiz I agree with @murphyte regarding the switch from 'artefact' to _'artifact'_. :bowtie: 
Thanks again!

**Comment by nicoleruiz** [comment]
All of these terms have been added.

**Comment by nicoleruiz** [comment]
SO:0002172 sequence_alteration_artifact
SO:0002174 deletion_artifact
SO:0002173 indel_artifact
SO:0002175 insertion_artifact
SO:0002177 duplication_artifact
SO:0002176 substitution_artifact
SO:0002179 MNV_artifact
SO:0002178 SNV_artifact
