### ISSUE TITLE
new term request: trinucleotide_expansion

### ISSUE THREAD

**Issue by ckongEbi** [The-Sequence-Ontology/SO-Ontologies#399]
Dear SO Team, 
 
    Can we request for a new term with details below? Please let us know if more details needed. 

```
term: trinucleotide_expansion
definition: Sequence of three nucleotide units repeated in tandem that can cause disease when expanded.
comment: Requested by Open Targets (EMBL-EBI), May 2017
```

Thanks
ck

**Comment by murphyte** [comment]
This would be a child of the proposed term "repeat_instability_region" from #386. We started off also using "expansion", but decided "instability" was better since these regions can both expand and contract, and the meaning of a term such as "trinucleotide_expansion" has a subtle conceptual shift depending on which allele you're annotating (is this a region that has already expanded, or could expand?). That is, a "trinucleotide_expansion" feature annotated on a region in GRCh38 (hopefully wildtype) might imply that it has already expanded to a disease-causing length. At least that's how we wound up looking at it.

-Terence Murphy

**Comment by ckongEbi** [comment]
We are trying to annotate variants from rare disease, which has already expanded. The "instability" term is aiming to define a sequence feature, as we wish to define a mutation consequence
e.g.  https://www.ncbi.nlm.nih.gov/clinvar/RCV000032099/

What is the scope of SO for mutations in general? thanks
ck

**Comment by nicoleruiz** [comment]
We would annotate that Clinvar variant as a type of insertion with the consequence of repeat_expansion. We recently added the term short_tandem_repeat_expansion (A short tandem repeat variant containing more repeat units than the reference sequence.) which is a type of sequence_variant. Would this work for you or do you need a more specific term to describe this variant? We can also add trinucleotide_repeat_expansion as a child of short_tandem_repeat_expansion.

**Comment by ckongEbi** [comment]
Hi, could you add trinucleotide_repeat_expansion as a child of short_tandem_repeat_expansion? please. 

Cheers,
ck

**Comment by nicoleruiz** [comment]
The new term is:
SO:0002165 trinucleotide_repeat_expansion - A short tandem repeat expansion with an increase in a sequence of three nucleotide units repeated in tandem compared to a reference sequence.
