### ISSUE TITLE
NTR small RNA

### ISSUE THREAD

**Issue by Antonialock** [The-Sequence-Ontology/SO-Ontologies#401]
Hello,

I would like to request a new term for small RNA (sRNA). They are <200 nts long. It should be a parent term to piRNA, siRNA, miRNA etc. I don't think it should be under ncRNA (though I think most are ncRNAs)

cheers
Antonia.

**Comment by ValWood** [comment]
I only looked at the abstract but  is sRNA what folks are using to describe all primary transcripts processed by the RNA machinery (I have never come across  it before and its rather a confusing term name). If  it is this it should probably be named something more explicit like
“primary transcript of RNAi processed RNA”
Need to provide a def, ref.

I would have placed this under ncRNA  (all are ncRNAs), but this might cause a problem because in SO ncRNAs are described as "mature transcripts". This will cause major annotation problems because  all of the RNAs which are processed into si/mi RNAs etc will be annoteted as ncRNA during  preliminary genome annotation. We only have information about the existance of the region providing the mature transcript, it would be *Impossible*  at present to annotate each processed variant. The  bio-community refers to these primary transcripts as ncRNAs

**Comment by Antonialock** [comment]
Do you have an alternative suggestion Val?

**Comment by ValWood** [comment]
An alternative to the one above?
To me it isn't really clear what is meant by "sRNA" from the SO ticket. Is it a primary transcript?

**Comment by Antonialock** [comment]
They are not primary transcripts
e.g. see
http://www.abcam.com/index.html?pageconfig=resource&rid=11860
https://en.wikipedia.org/wiki/Small_RNA

**Comment by ValWood** [comment]
So what are they? If they are processed, how do they differ from siRNAs?

**Comment by ValWood** [comment]
I'm looking at the eiked=edia article and it isn't clear


Small RNA are <200 nt (nucleotide) in length, and are usually non-coding RNA molecules.[1] RNA silencing is often a function of these molecules, with the most common and well-studied example being RNA interference (RNAi), in which endogenously expressed microRNA (miRNA) or exogenously derived small interfering RNA (siRNA) induces the degradation of complementary messenger RNA. 

To me this sounds like this is the ncRNA from which siRNAs are derived (aren't the siRNAs the part that associates with RISC? not the full length one?
In which case it is a primary transcript.

If not I'm still not understanding what it is?

**Comment by Antonialock** [comment]
from the abcam article:
Small non-coding RNAs come in different forms, the best understood being small interfering RNAs (siRNAs), microRNAs (miRNAs) and Piwi-associated RNAs (piRNAs). These small RNAs are made by processing longer precursor RNAs into small functional RNAs. The processing of siRNAs and miRNAs occurs in multiple steps and involves specific enzymes, including Dicer and/or Drosha. By contrast, the processing of piRNAs occurs independently of Drosha and Dicer. Once processed, the small RNAs associate with members of the Argonaute family and form so-called RISC complexes.

**Comment by ValWood** [comment]
Ah so small interfering RNAs are siRNAs? Its just a collective name for any  small interfreing RNA?

You could just use siRNA which are the form of RNA found in pombe? Or are piRNAs found too?

**Comment by Antonialock** [comment]
piRNAs are found, and small rRNAs are also bound by dcr1

**Comment by ValWood** [comment]
Got it!

**Comment by Antonialock** [comment]
Hello! Is it possible for someone to have a look at this soonish please?

**Comment by nicoleruiz** [comment]
Can you provide a definition for the term?

**Comment by Antonialock** [comment]
They are mature transcripts yes in that they are typically modified from longer transcripts.
I don't know of any examples that are *not* ncRNAs so it seems like it would be safe to put the term there.

Def:
Small noncoding RNAs (sRNA) includes short ncRNAs such as piRNA, miRNA and siRNAs (among others). These RNAs are less than 200 nts long and are involved in genome regulation.

**Comment by keilbeck** [comment]
Sorry - this request got a little messy. There is already a similar-ish term in the SO, that has the same child terms you seem to be looking at. SO:0000370 small_regulatory_ncRNA in SO already with the definition “A non-coding RNA, usually with a specific secondary structure, that acts to regulate gene expression.”.
 
miRNA is a child of small_regulatory_ncRNA and siRNA, piRNA and small_regulatory_ncRNA are children of ncRNA.

It would make sense to me to adjust the definition of small regulatory ncRNA and move the child terms accordingly rather than to add a new term to the mix. Also - this means that all of these transcripts would have to be non coding. This is in agreement with Val - but I want to check with antonia that she is OK with that as her first comment is at odds with that definition. If you want to have a term for both coding and non coding small transcripts this would be really gnarly as it goes against the structure of the ontology.

**Comment by Antonialock** [comment]
Hi Karen, I think that's fine....I don't think there are any known examples that are not ncRNA

**Comment by nicoleruiz** [comment]
I modified the definition of SO:0000370 small_regulatory_ncRNA and moved SO:0001035 piRNA and SO:0000646 siRNA to make these children of small_regulatory_ncRNA. The new definition of small_regulatory_ncRNA is "A non-coding RNA less than 200 nucleotides long, usually with a specific secondary structure, that acts to regulate gene expression. These include short ncRNAs such as piRNA, miRNA and siRNAs (among others)."

**Comment by Antonialock** [comment]
Thanks!
