### ISSUE TITLE
selection_marker

### ISSUE THREAD

**Issue by bbartley** [The-Sequence-Ontology/SO-Ontologies#402]
Hi,

I'd like to suggest selection_marker as a kind of gene. This would be helpful for annotating plasmids.

Thanks
Bryan Bartley
PhD Student
UW Bioengineering

**Comment by davidwsant** [comment]
Hi Bryan,

The new term selection_marker has been added. It has received the ID SO:0002232. The SO browser should be updated with this term by tomorrow morning. I apologize that it took almost three years to have this term updated due to the change in staff. Thank you for your patience.

Best,

Dave

**Comment by bbartley** [comment]
@davidwsant Thanks very much!  Very exciting to see this update, and it will come in very useful!
