### ISSUE TITLE
gff3_validator fails to use provided SO OBO ontology file

### ISSUE THREAD

**Issue by whlavina** [The-Sequence-Ontology/SO-Ontologies#405]
The gff3_validator tool offers a command-line argument, --so_file, to specify an SO OBO ontology file. Unfortunately, the code does not actually use the file, since it fails to pass it to the relevant function.

Specifically, the call to parse_so_file() in this code has a bug:

```
sub validate_gff3 {
  my ($gff3_file, $so_file) = @_;
  my ($so_data) = parse_so_file();
```

This should be changed to:

```
sub validate_gff3 {
  my ($gff3_file, $so_file) = @_;
  my ($so_data) = parse_so_file($so_file);
```

**Comment by davidwsant** [comment]
Hi Wratko, 

I apologize for the delayed response. The SO team had a change in staff and issues were not reviewed for some time. I am now returning to old issues that have not been seen.

It appears as though this issue is actually about gff3_validator, which is not maintained by the SO team. I would recommend resubmitting this request on the [gff3_validator GitHub page](https://github.com/solgenomics/gff3_validator). I did not find the loop you had mentioned in any of the code, so the scripts may have been updated. I hope you find a solution.

Good luck,

Dave Sant

@whlavina
