### ISSUE TITLE
Clarify definitions of "sense" and "antisense"

### ISSUE THREAD

**Issue by rhdolin** [The-Sequence-Ontology/SO-Ontologies#418]
Greetings,
We are adding a field to the FHIR Sequence resource, to differentiate Sense vs. Antisense. The definitions we are proposing: "A relative reference to a DNA strand based on gene orientation. The strand that contains the gene is the "sense" strand, and the opposite complementary strand is the "antisense" strand".

We did not find "sense" in Sequence Ontology. Also, we didn't use Sequence Ontology's "antisense" because antisense is a child of overlapping (SO:0000068), which is more restrictive than we wanted - we simply want to reference the strand opposite the coding sequence. 

HL7 Genomics Committee members suggested that we submit a comment here, to see if it might make sense to include "sense orientation" and "antisense orientation" into Sequence Ontology?
Thank you.

**Comment by davidwsant** [comment]
Hi @rhdolin,

I am going to ask for an opinion from Terrence Murphy @murphyte as he knows quite a bit about ontology structures and biological models and he might have some good input here. 

I agree that it would be good to add these terms, but I am not certain where I should put the terms. They are not is_a "chromosome_part" , because they are referring just to the orientation. They also are not "gene" or anything under gene.
Maybe it could go under one of the children terms of "experimental_feature" SO:0001410? That still doesn't seem correct. 

Terrence, do you have any suggestions?

Thanks,

Dave

**Comment by murphyte** [comment]
Hi @rhdolin - can you give an example of where you would use these terms in a context that would benefit from having them in SO? I mostly work with the SO sequence_feature branch, and some under sequence_variant, whereas these terms are probably more appropriate under sequence_attribute. But the problem I'm having is that they are relative to something else. That is, a gene feature (and its child features) are inherently "sense", and there is isn't a feature I would define on a genomic sequence that would be appropriate to have an "antisense" attribute (the identical feature(s) but with the reverse strand wouldn't be appropriate to call gene/mRNA/CDS). Even on an RNA/cDNA sequence it would be a bit odd to define a feature on the reverse strand that would have an "antisense" attribute.

The other context where the terms are common is in describing first-cycle/second-cycle cDNA synthesis or similar in probe design. That usage is definitely cleaner, but it's more descriptive than used in a context that I normally think of as benefitting from SO (GFF3, GVF). 

So if you could give an example context it might help illuminate what the appropriate relationships might be.

**Comment by rhdolin** [comment]
Hi @murphyte 

At the time we submitted these requests, the FHIR Genomics Sequence resource was treating 'Watson' and 'Sense' as synonymous (http://hl7.org/fhir/STU3/sequence-definitions.html#Sequence.referenceSeq.strand). As I recall, our primary use case was to establish that 'Watson' (absolute) and 'Sense' (relative) were different, in synch with Sequence Ontology. This has since been resolved (http://hl7.org/fhir/R4/molecularsequence-definitions.html#MolecularSequence.referenceSeq.strand), so I'm not sure I really still have a compelling use case. I did struggle a bit in the past trying to understand why, for instance, ATXN8OS is on the Watson strand and classified as an antisense_RNA, only to finally realize that in this case, antisense referred to the relationship between ATXN8OS and KLHL1 - so, the only use case that comes to mind is that sense and antisense might be thought of like CIS and TRANS in that they can indicate if two genes on a given molecule are on the same vs. different strands.

**Comment by murphyte** [comment]
> only to finally realize that in this case, antisense referred to the relationship between ATXN8OS and KLHL1

Yes, this is a bit of a problem with the usage of antisense_RNA (SO:0000644), which also happens to be missing a corresponding antisense_RNA_gene term. The SO definition isn't the same as INSDC's (http://www.insdc.org/rna_vocab.html) or Ensembl's (https://m.ensembl.org/info/genome/genebuild/biotypes.html), further complicating the matter. I generally avoid the term because it's somewhat ambiguous (is it antisense relative to the mature mRNA of the other gene, or just the hnRNA), and it also implies a regulatory relationship that may or may not exist.

If your need is met by the ticket on Watson/Crick, then I suggest we just close this ticket. The issues I raise above about antisense will be addressed separately at some point in the future.

**Comment by rhdolin** [comment]
Thank you @murphyte. Closing this ticket works for me.

**Comment by davidwsant** [comment]
Thank you for helping straighten this out. 

Best,

Dave
