### ISSUE TITLE
What is the proper term to use for "IUPAC" codes?

### ISSUE THREAD

**Issue by jdetras** [The-Sequence-Ontology/SO-Ontologies#431]
Hi,

We are using using the IUPAC nucleotide codes in our database (eg. R, W, Y etc). What is the equivalent or correct term to use? Should it be "IUPAC_nucleotide_code" or something else?

Thanks,
Jeff

**Comment by davidwsant** [comment]
Hi Jeff,

Thank you for the suggestion. I understand why you are wondering what you should use here. Unfortunately, I do not know the best way to add something that is only a single base. If it is 'a', I can give the term the name of 'adenine'. However, if it is something like 'R' then I don't know what I should use. I do not want to use a single letter as the term name, but adding a term 'a_or_g' seems a bit odd. 

If these are added, then I suggest we add them as children of SO:0001236 (base). The [IUPAC documentation](http://www.ebi.ac.uk/embl/Documentation/FT_definitions/feature_table.html) does not discriminate between RNA and DNA bases, so they do not need to be split up. 

My biggest concern is choosing an appropriate name. I am going to close this issue request because it is over 2 years old and some of our submitters have little concern about the term after that amount of time. However, I think this is a valid concept to put in the SO so I will forward this idea to others in our group. If you are still working on these concepts, please feel free to reopen the issue. 

Thanks,

Dave
