### ISSUE TITLE
Requesting to add "KASP_marker" as a "genetic_marker"

### ISSUE THREAD

**Issue by jdetras** [The-Sequence-Ontology/SO-Ontologies#432]
KASP is a marker technology and I am requesting to add the term "KASP_marker" as a child of "genetic_marker" like "DArT_marker" (http://www.sequenceontology.org/browser/current_svn/term/SO:0001646). Is this a valid request? Thanks.

**Comment by davidwsant** [comment]
Hi @jdetras,

I apologize for the long delay since your issue request was submitted. We had a chance in staff and I am now trying to go through old issue requests.

In the past few months we have changed several things about the setup of several things in the GitHub page, including adding templates for new term requests. We are not familiar enough with the term KASP and I am not finding enough literature to be able to determine the best course of action. If you could please submit a new issue request following [this template](https://github.com/The-Sequence-Ontology/SO-Ontologies/blob/master/.github/ISSUE_TEMPLATE/new-term-request.md), that would be greatly appreciated. In particular, please include a full definition that you wish to accompany the term and references to publications that use this term. 

Thank you,

Dave
