### ISSUE TITLE
Child groups of the downstream_gene_variant and the upstream_gene_variant groups.

### ISSUE THREAD

**Issue by DSuveges** [The-Sequence-Ontology/SO-Ontologies#433]
Hi Guys,

There's a thing that is not clear to me in the above mentioned groups. For example the [downstream_gene_variant](http://www.sequenceontology.org/miso/current_svn/term/SO:0001632)

The diagram says that the 500B_downstream_variant, 2KB_downstream_variant and 5KB_downstream_variants are disjunct child groups of the downstream_gene_variant group. However, the documentation suggests that the downstream_gene_variant group 
has 5KB_downstream_variant ("A sequence variant located within 5 KB of the end of a gene.") as the child group, which has the 2KB_downstream_variant ("A sequence variant located within 2KB 3' of a gene.") as child, which has 500B_downstream_variant ("A sequence variant located within a half KB of the end of a gene.") as a child. I might get these things wrong, I would appreciate if you could clarify this. 

Thanks a lot!
Best,
Daniel

**Comment by davidwsant** [comment]
Hi @DSuveges,

I believe you understand the terms correctly. It is true that there is overlap between the terms. For instance, if a variant is 300 bp downstream of the gene then you could potentially mark it as any of the 3 child terms of downstream_gene_variant. However, the most appropriate one would be 500B_downstream_variant because it is the most limiting. Does this make sense?

Thanks,

Dave
