### ISSUE TITLE
discussion about motif v element v site

### ISSUE THREAD

**Issue by RLovering** [The-Sequence-Ontology/SO-Ontologies#460]
So that this is recorded below is a summary of a discussion about this issue:

Julio:
>More precisely a "site" is better called a transcription factor binding site TFBS
>I think "element" is too general and may refer to almost anything. In the bacteria literature people dont use "element" to refer to TFBSs

Jacques:
>Beware, a motif is a summary representation of the specificity of a transcription factor, usually built by summarizing the information from a collection of aligned site sequences. 
>What can exert a regulatory effect (activator or repressor) on a gene is not a motif, but a site (a sequence found at a given position of the genome), not a motif.

**Comment by davidwsant** [comment]
Hi @RLovering,

This issue was also fixed up last summer, but I did not close the issue. You can see the term [TF_binding_site](http://sequenceontology.org/browser/current_svn/term/SO:0000235) on the SO browser if you would like to see how it is arranged now. I believe it should match the conclusions of the group discussion. 

Thanks,

Dave
