### ISSUE TITLE
Document an SOP for external users to make a PR

### ISSUE THREAD

**Issue by cmungall** [The-Sequence-Ontology/SO-Ontologies#463]
I can help with this, but will need guidance from @nicoleruiz and @keilbeck as I don't know the current workflow. I think @mikebada and @msinclair2 should be able to help, we should be aiming for aligned SOP for MSO

Note: this may be easier to do *after* refactoring the repo: #462

However, in order to help @sabrinatoro help, we can provide some guidance for the current repo. @nicoleruiz:

 * Which file is the source file you edit? Is it so.obo or so.owl
 * Do you use oboedit or Protege
 * How do you assign ID ranges? Do you have an idranges file as is currently standard (see #462)
 * How do you build downstream products once you edit the source? Do you run OORT manually?

Once you answer these I can help come up with the SOP

**Comment by mikebada** [comment]
I'm willing to answer any questions I can, but I first need to make sure I understand the acronyms, ha ha: SOP = standard operating procedure?  And what is PR?

**Comment by msinclair2** [comment]
I think I can answer these questions.  I also want to know what PR is.

so.obo is the file that is edited.

obo-edit is the editor used.

I don't think any ID ranges are assigned, if you mean ranges assigned to different editors.

OORT is run manually to build downstream products.

Is this right @nicoleruiz ?

**Comment by cmungall** [comment]
PR = pull request.

OK, can you clarify, is so.obo still edited or is the mso file the source?

I strongly recommend assigning blocks of ID ranges, and having the ID ranges be in a file in github

For more background on standard github ontology setup and workflow practices, see:

https://docs.google.com/presentation/d/1nIybviEEJiRKHO2rkBMZsQ0QjtsHyU01_-9beZqD_Z4/edit#slide=id.p

And I recommend experimenting with:

https://github.com/INCATools/ontology-development-kit

Use it to generate a fake ontology repo, and then look at the generated internal documentation

**Comment by nicoleruiz** [comment]
Sorry just saw this ticket. 

@msinclair2 yes everything you said is correct. 

In obo-edit, we have set an ID profile for SO. This is the rule we use: SO:$sequence(7,0,9999999)$

**Comment by msinclair2** [comment]
Thanks, Nicole.  But, I don't know what an ID profile or rule in obo-edit is.

**Comment by cmungall** [comment]
@msinclair2 I recommend using the ODK to create an example github repository according to standard conventions. This will give you an idranges file, plus a README-editors.md file that includes information on how the idranges file is used.

This is the template:

https://github.com/INCATools/ontology-development-kit/blob/master/template/src/ontology/README-editors.md.jinja2

Recall we set up an idrange for you for you to make PRs on RO: https://github.com/oborel/obo-relations/pull/233

The rule that @nicoleruiz is showing is analogous to the new entity creation preferences form in Protege.

@nicoleruiz it is standard it include an id-profiles file in the github repository that states what the range is for each person editing. This is necessary to avoid clashes. How do you manage this in SO at the moment?

**Comment by davidwsant** [comment]
Hi guys, my name is Dave and I am the new postdoc that is going to work on this. @nicoleruiz has shown me how to edit the so.obo files, but I could not get owl tools to help me generate the other files because of compatibility issues on my computer. She had to take care of it for me last time. 

Nicole has suggested that I learn to use Protege instead because it the program that is still supported. She has sent me some tutorials from Mike and Michael that I will look through when I get the chance. @cmungall, Nicole has suggested that you would be very familiar with Protege and Robot, do you mind if contact you if I run into issues running the programs?

Thanks!

**Comment by cmungall** [comment]
Hi David,

I recommend subscribing to

https://groups.google.com/forum/#!forum/obo-tools

There's a small group of us on obo-tools that are developing ROBOT etc -
you'll get faster responses than if you just email me

I also recommend subscribing too
https://groups.google.com/forum/#!forum/obo-discuss

**Comment by davidwsant** [comment]
Thank you for the help. I will do as you suggested.

**Comment by davidwsant** [comment]
Hi @cmungall,

I have finally updated the SO repository to be able to effectively work with pull requests. I have included as much information in the README as I thought could help. As far as I am aware, MSO is no longer being updated along with the SO, so for now I think we should only focus on SO. 

Until now, our group has been editing the so.obo file, but the Makefile can run with either so.owl or so.obo. I have included this info in the README so that editors will be aware that they can work with either file. 

I am still working with OBOedit, but have been practicing working with Protege. However, as far as I am aware, the build will end with the same output. 

@nicoleruiz mentioned how we assigned the ranges. The last few that I have added have been given the IDs SO:0002226-SO:0002231. These are not the highest IDs, as one of the oldest terms (gene_segment) actually has the ID SO:3000000. 

The downstream products are now created using the Makefile, which uses OWLTools Ontology Release Tool. 

Your other issue request mentions using underscores instead of spaces and no special characters in terms. This is not yet in the README--do you think it should be included? 

Do you think there should be a separate SOP from the README.md document that is now included with the repository? Is there any other info that needs to be included in the README? 

Thanks,

Dave

**Comment by cmungall** [comment]
Hi Dave

I think you should settle on one file being the source, and derive everything from that. I would use the so.obo file, so you can edit using either OE or Protege. It's conventional to call this something like so-edit.obo, but what you have set up seems like a great first step!

For the IDs I recommend an ID ranges file to document which range each editor has

**Comment by diekhans** [comment]
I am happy to server as an alpha tester for the SOP.  There is a
PR I want to submit to fix an open ticket.

**Comment by davidwsant** [comment]
Hi @diekhans,

I am sorry nobody has gotten to the issue requests. When I joined the group, a graduate student had kindly volunteered some of her time to update requests even though it had nothing to do with her project. Once she graduated, it was left alone until I was able to take over. I have not looked at any of the requests from before 2019. If you would like to try generating your own files and sending a pull request, I would be glad to use it as a test case to see if this will work as well as I hope it does. I believe all of the instructions for using the Makefile are on the README.md. It requires OWLTools, but I have found that most people that know ontologies are familiar with OWLTools. Let me know if any info is missing or it doesn't work and I will try to respond as quickly as I can. 

Thanks,

Dave

**Comment by keilbeck** [comment]
Dave, it was part of Nicole’s project and she published on it. Not sure where you got that idea from.

**Comment by davidwsant** [comment]
Hi @cmungall,

I have added an edit file, so-edit.obo. I have updated the Makefile to work from so-edit.obo, as you have suggested. 

I have a couple of questions about the ID ranges, however. The Eilbeck lab has currently used IDs for SO:0000001-SO:0002234. I was thinking perhaps we could block off perhaps up through SO:0004000 for our group. For the past several years we have had one person in the group update the files, so I think a single range for our group should be sufficient. Should we make a range for pull requests? I was thinking perhaps from SO:0004001-SO:0005000 might be more than enough. We do not have any terms used between SO:000234 and SO:0005836, so I thought that range would be appropriate. You have more experience with this, so I would like your opinion--what do you think? Do you think a single range for pull requests is sufficient until we have more than one group submitting pull requests? 

Additionally, as for making a record of which ranges are available for which editors, do you just put this in a text file like perhaps "ID_ranges.txt"? I was thinking there could just be one line per editor with the info about the ranges to use, such as "Eilbeck Lab: SO:0000001-SO:0004000". What have other groups done? 

Thanks,

Dave

**Comment by cmungall** [comment]
The danger is from clashing IDs, that's why it's best to assign a range to
either an individual (or a collection of individuals who are internally
coordinated if they have their own mechanism for avoiding clashes.. but
really I would recommend individuals)

it's a bit of a pain to set up but only has to be done once per
contributor, and most ontologies have a relatively low number of
contributors that can get over the hurdle of using protege or oboedit

It's up to you whether the id-ranges file is a txt file or the more
standard owl file, it's more of a social mechanism. The person making the
PR for a new term has to know they have to do some Protege configuration to
assign things in a range. But everything should all be in the same file

You could also try other workflows. E.g. external people just use a UUID,
and then you and the core editors would replace these with IDs. But you'll
want mechanisms in place to stop these escaping

**Comment by davidwsant** [comment]
Hi @cmungall,

I have created a tab-delimited text file ID_ranges.txt that contains the ranges that should be used by different groups. I have added information about this in the README.md so that contributors will know to use IDs in a certain range. I also mentioned that they can create an issue request to ask for ranges and I can reserve a range for their group. I think this fulfills everything in your issue requests. I hope SO is fully ready for pull requests now. Please let us know if anything else needs to be updated.

Thanks,

Dave

**Comment by cmungall** [comment]
perfect thanks!
