### ISSUE TITLE
Term request: self_cleaving_ribozyme

### ISSUE THREAD

**Issue by JS3xton** [The-Sequence-Ontology/SO-Ontologies#470]
The [SBOL Visual community](http://sbolstandard.org/visual/) would like to describe a self-cleaving ribozyme insulator part with an appropriate Sequence Ontology term, and we feel the term "ribozyme (SO:0000374)" is too general. Towards addressing this, we would like to request a more specific term for self-cleaving ribozymes:

>Term: self_cleaving_ribozyme
>Description: An RNA that catalyzes its own cleavage.
>is_a SO:0000374 (ribozyme)
>has_quality SO:0001977 (Ribonuclease Site)

Examples include [hammerhead ribozymes](https://en.wikipedia.org/wiki/Hammerhead_ribozyme) and [hairpin ribozymes](https://en.wikipedia.org/wiki/Hairpin_ribozyme).

Discussions within our community related to this request can be found here: https://groups.google.com/d/topic/sbol-visual/bnAIUlvyBXQ/discussion.

If adopted, the "hammerhead_ribozyme (SO:0000380)" term might more appropriately be positioned as a child of the adopted "self_cleaving_ribozyme" term.

**Comment by davidwsant** [comment]
Hi @JS3xton,

I am sorry it has taken me so long to get back to looking at issue requests. I have added term self_cleaving_ribozyme (SO:0002231) def: "An RNA that catalyzes its own cleavage." The SO browser should update tomorrow.
I decided to not add hammerhead or hairpin ribozymes at this time, but if you are going to use those terms for an upcoming project you are welcome to open another issue request. I have created some issue templates for SO that should make it easier to generate new issue tickets.

Thanks,

Dave Sant

**Comment by JS3xton** [comment]
Great, thanks Dave!

Hammerhead ribozyme already has an SO term ([SO:0000380](http://www.sequenceontology.org/browser/current_release/term/SO:0000380)). It may now more appropriately belong as a child (i.e. `is_a`) of self_cleaving_ribozyme ([SO:0002231](http://www.sequenceontology.org/browser/current_release/term/SO:0002231)).
