### ISSUE TITLE
Appropriate term for 2A sequences?

### ISSUE THREAD

**Issue by jakebeal** [The-Sequence-Ontology/SO-Ontologies#475]
We are looking for a good term for a 2A self-cleaving peptide (see [SBOL Visual issue 70](https://github.com/SynBioDex/SBOL-visual/issues/70)).  The SO cleaved_peptide_region ([SO:0100011](http://sequenceontology.org/browser/current_release/term/SO:0100011)) doesn't seem to match, because it references maturation, while a 2A creates cleavage via a translational skip.

Can you please help resolve this lack of a term, by either:
1. pointing us to a matching term that we have failed to find, 
2. adjusting the description of SO:0100011 to include translational skip, or
3. adding a new "2A self-cleaving peptide" term as a child of [polypeptide region](http://sequenceontology.org/browser/current_release/term/SO:0000839)

Whichever resolution you think best would be fine.

**Comment by jakebeal** [comment]
Bump to @davidwsant for attention.

**Comment by davidwsant** [comment]
Hi @jakebeal, 

Would you mind giving me a couple of proposals? Because you are more familiar with this than those in our group, I believe you are likely to have good input. Additionally, do you have a publication or two that we can reference for this change? 

If you were to create a new term 2A_self_cleaving_peptide, could you give an example of a definition you would consider appropriate? 

Would you mind also giving an example of how you would change the current definition if that were the route taken? The cleaved_peptide_region definition is currently: The cleaved_peptide_region is the region of a peptide sequence that is cleaved during maturation.

I think it is likely that the term 2A_self_cleaving_peptide will be added, but I will bring both to the group and see which they believe is best. 

Thank you,

Dave Sant

**Comment by jakebeal** [comment]
Hi, @davidwsant, 

Here are some references for 2A sequences:
- https://en.wikipedia.org/wiki/2A_self-cleaving_peptides (not scientific, but a nice clear intro with references)
- https://www.nature.com/articles/s41598-017-02460-2
- http://cshprotocols.cshlp.org/content/2012/2/pdb.ip067876

With regards to definition, I think the new term is likely a better approach, since the 2A sequence includes areas that do _not_ get cleaved as well as areas that do get cleaved.  My suggested definition for `2A_self_cleaving_peptide` would be:
> A 2A_self_cleaving_peptide is a polypeptide region that can result in a break in the peptide sequence at its terminal G-P junction.

If you went instead with a change to the current definition of `cleaved_peptide_region`, a possible rewrite would be:
> "The cleaved_peptide_region is the region of a peptide sequence that is cleaved or otherwise omitted during maturation"

**Comment by davidwsant** [comment]
Hi @jakebeal,

I apologize for the delay, other members of the team have been busy. As per your request, I have added a new term "2A_self_cleaving_peptide_region", which received the ID SO:0002224. This has been pushed to GitHub and should be updated on our website by tomorrow morning. Thank you for your suggestions.

Thanks,

Dave

**Comment by jakebeal** [comment]
Excellent - thank you!
