### ISSUE TITLE
Spurious protein terms

### ISSUE THREAD

**Issue by Alexbateman1** [The-Sequence-Ontology/SO-Ontologies#478]
I was not able to find a couple of terms that I think would be useful additions to SO. The protein sequence databases contain an unknown but significant number of spurious proteins. These are not translated in nature.  In general spurious proteins are created by automated gene calling pipeline errors. My group has been involved in producing software and databases to identify and track these (PMID:29721311 and PMID:22434837). I would suggest a general term of "Spurious protein" that could perhaps live in polymer_attribute.  A specific type of spurious protein is known as a Shadow ORF. These are generally found on the opposite strand of a known gene. I would suggest that "Shadow ORF" as a new term that lives under the "Spurious protein" term. It is worth noting that shadow ORFs have been found on the opposite strand to non-coding RNA genes such as rRNA.

**Comment by davidwsant** [comment]
Hi @Alexbateman1,

I am sorry it has taken so long to get to this request. I agree that this term would be relevant. However, I do not know that it belongs under polymer_attribute. I think it might be better suited under this term:
[SO:0001410](http://sequenceontology.org/browser/current_svn/term/SO:0001410),  experimental_feature, def: "A region which is the result of some arbitrary experimental procedure. The procedure may be carried out with biological material or inside a computer." 

What do you think?

As for the articles that you have added, I think they are important papers, but I do not think they should be included in the SO as they are for specific programs rather than papers about the terms themselves. I found one paper that is pretty good for describing suprious proteins, [PMID:21771858](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3203614/). However, I cannot find any papers that mention shadow ORF except for the papers that you have provided. Are you aware of any publications that specifically mention shadow ORF that are not papers specifically about programs for predicting them? 

One more thing I wanted to ask about was a specific definition. Here is what I have, but this may need changing before I add it to the so.

spurious_protein: def: "A region of DNA that is predicted to be translated and transcribed into a protein by a protein detection algorithm that does not get transcribed in nature."

Can you please give me a specific definition for shadow_orf?

Thanks,

Dave

**Comment by davidwsant** [comment]
Hi @Alexbateman1,

The new term spurious_protein (SO:0002248) has been added to the SO. The [SO Browser](http://sequenceontology.org/browser/current_svn/) will be updated with the new term within about 24 hours.

Thanks,

Dave
