### ISSUE TITLE
Distinguish between small and large subunit rRNA in organelles

### ISSUE THREAD

**Issue by AntonPetrov** [The-Sequence-Ontology/SO-Ontologies#493]
**SO term name and accession**
[mt_rRNA (SO:0002128)](http://sequenceontology.org/browser/current_release/term/SO:0002128)

**Parent term name and accession**
[rRNA (SO:0000252)](http://sequenceontology.org/browser/current_release/term/SO:0000252)

**Suggested new parent term name and accession**

The current location of mt_rRNA as a sibling term to LSU and SSU rRNA does not allow to distinguish between cytoplasmic and organellar mt_rRNAs, which have very distinct, usually more compact, structures compared to the cytoplasmic counterparts. 

Perhaps the rRNA subtree could look something like this:

rRNA
----cytoplasmic rRNA
--------small subunit cytoplasmic rRNA
--------large subunit cytoplasmic rRNA
----organellar rRNA
--------mt_rRNA
------------small subunit mitochondrial rRNA
------------large subunit mitochondrial rRNA
--------plastid_rRNA
------------small subunit plastid rRNA
------------large subunit plastid rRNA

There could be other solutions, for example, one could introduce `mito_large_subunit_rRNA` and `plastid_large_subunit_rRNA` as child terms under `large_subunit_rRNA` (similar for SSU).

**Reason for the change**
In addition to clarifying the rRNA subtree hierarchy, the change would allow [RNAcentral](https://rnacentral.org) to enable better searches for rRNAs, as we can classify mtRNAs into LSU and SSU subtypes for mitochondria and plastids. 

My colleague Blake Sweeney @blakesweeney is in the process of switching RNAcentral to using Sequence Ontology as the main RNA types classification, and it would really help our users if we could consistently annotate rRNAs which is one of the largest sequence classes in RNAcentral. Here is our [current rRNA subtree](https://test.rnacentral.org/search?q=RNA%20AND%20so_rna_type_name:%22RRNA%22) but it would be so much nicer if mtRNAs could be organised as SSU and LSU:

![Screenshot 2020-08-27 at 16 19 39](https://user-images.githubusercontent.com/432675/91461606-1d67f980-e881-11ea-9791-d3bc23fa147e.png)

**Relevant Publications**
https://pubmed.ncbi.nlm.nih.gov/3044395/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4008552/

Please let me know if you have any questions and many thanks in advance for looking into this!

**Comment by AntonPetrov** [comment]
👋 Hello! Just wanted to let you know that RNAcentral has now switched to using Sequence Ontology terms as the main classification of RNA types. You can now [browse RNAcentral by SO term](https://rnacentral.org/search?q=RNA) using the RNA type facet.

Are there any updates on this issue regarding rRNAs? As we continue to improve the RNAcentral algorithms for assigning SO terms, rationalising parts of the ncRNA SO subtree would really help us and our users.

Many thanks for looking into this!

**Comment by sjm41** [comment]
+1 to this request

**Comment by davidwsant** [comment]
Hi guys,

@sjm41 
@AntonPetrov 

I think it makes sense to use the first structure that you proposed. This would involve creating several terms and moving a couple of terms. Below are my proposed changes for how to make this happen. Please look through all of my proposed changes, especially definitions and locations to help me make sure that I have not made any mistakes. I used markdown indenting. It looks a little funny, but I think you can see how it is structured without a problem. 


- **New Term**
+ [Term]
+ id: SO:new
+ name: organellar_rRNA
+ def: "rRNA (SO:0000252) that derives   from the genome of an organelle rather than from the nucleus of a cell." [PMID:3044395]
+ synonym: "organellar rRNA"  EXACT []
+ synonym: "organellar ribosomal RNA" EXACT []
+ is_a: SO:0000252 ! rRNA

  - [Term]
  - id: SO:0002128
  - name: mt_rRNA
  - def: "Mitochondrial ribosomal   RNA." [GENCODE:http\://www.gencodegenes.org/gencode_biotypes.html]
  - synonym: "mitochondrial_rRNA"   EXACT []
  - synonym: "Mt_rRNA" EXACT []
  - **is_a: SO:new!   organellar_rRNA**


    - **New Term**
    - [Term]
    - id: SO:new
    - name: mitochondrial_large_subunit_rRNA
    - def: "mitochondrial rRNA (SO:0002128) transcripts that are structures of the large subunit of mitochondrial RNA" [PMID:3044395, PMID: 24572720]
    - synonym: "mitochondrial large subunit rRNA" EXACT []
    - is_a: SO:0002128 ! mt_rRNA
   

    - **New Term**
    - [Term]
    - id: SO:new
    - name: mitochondrial_small_subunit_rRNA
    - def: "mitochondrial rRNA (SO:0002128) transcripts that are structures of the small subunit of mitochondrial RNA" [PMID:3044395, PMID: 24572720]
    - synonym: "mitochondrial small subunit rRNA" EXACT []
    - is_a: SO:0002128 ! mt_rRNA

  - **New Term**
  - [Term]
  - id: SO:new
  - name: plastid_rRNA
  - def: "rRNA transcribed from the genome of a plastid such as a chloroplast." [PMID:3044395, PMID: 24572720]
  - synonym: "plastid rRNA" EXACT []
  - is_a: SO:new! organellar_rRNA

    - **New Term**
    - [Term]
    - id: SO:new
    - name: plastid_small_subunit_rRNA
    - def: "plastid rRNA (SO:0002347)   transcripts that are structures of the small subunit of RNA of a plastid such   as a chloroplast." [PMID:3044395, PMID: 24572720]
    - synonym: "plastid small subunit   rRNA" EXACT []
    - is_a: SO:new! plastid_rRNA

    - **New Term**
    - [Term]
    - id: SO:new
    - name: plastidl_large_subunit_rRNA
    - def: "plastid rRNA (SO:0002347)   transcripts that are structures of the large subunit of RNA of a plastid such   as a chloroplast." [PMID:3044395, PMID: 24572720]
    - synonym: "plastid small large   rRNA" EXACT []
    - is_a: SO:new! plastid_rRNA

Best,

Dave

**Comment by sjm41** [comment]
Hi Dave

Looking good. Three comments:

1. Typo in "plastidl_large_subunit_rRNA"

2. Anton also suggested having a new grouping term for the current 'large_subunit_rRNA' and 'small_subunit_rRNA' terms - he suggested "cytoplasmic rRNA". Also suggested renaming those two existing terms accordingly.

3. Related to above, should we define these different rRNAs based on their origin (nuclear genome, mito genome, plastid genome) or where they function?  Anton's "cytoplasmic rRNA" uses the latter, whereas the new definitions of 'organellar_rRNA' and 'plastid_rRNA' above use the former.  Defining based on location of function seems to make more sense to me, but I'm unsure if the SO has an existing precedent one way or the other?

**Comment by murphyte** [comment]
Do you want to add any groups for prokaryotic vs eukaryotic rRNAs? The current large_subunit_rRNA and small_subunit_rRNA SO terms are parents of both, and I guess it's fine to consider the prokarotic rRNAs to be "cytoplasmic". But if it's valuable to designate the rRNA terms that are specific for organelles, then it seems reasonable to do the same for prokaryotic subunits?

**Comment by AntonPetrov** [comment]
@davidwsant Thank you for looking into this Dave!

Your proposed subtree makes sense to me (reproducing below in a condensed form):

```
organellar_rRNA
---- mt_rRNA
-------- mitochondrial_small_subunit_rRNA
-------- mitochondrial_large_subunit_rRNA
---- plastid_rRNA
-------- plastid_small_subunit_rRNA
-------- plastid_large_subunit_rRNA
```

As pointed out by Steven, I do still think that it's important to have a new grouping for the current `large_subunit_rRNA` and `small_subunit_rRNA` terms to better distinguish between the "main" cytoplasmic rRNA and the "symbiotic" rRNAs found in the organelles.

@murphyte As you say, I think it's fine to call prokaryotic rRNAs cytoplasmic. I can see that it can be useful to distinguish the eu- and prokaryotic rRNAs but I don't have a strong opinion on this.

@sjm41 I am a bit confused by [your point 3](https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/493#issuecomment-828253692) about origins vs location of function. The mito_rRNAs are encoded in the mito genome and function in the mitochondria (same for the plastids), so the origin and the location seem to be the same (unless I misunderstood your point)?

**Comment by sjm41** [comment]
Hi @AntonPetrov 

My point 3 was thinking about the name and (more importantly!) the definition of the proposed "cytoplasmic rRNA" group/names, and making the def consistent with the defs for mitochondrial/plastid rRNA.

I agree it makes sense to name/group the 'main' rRNAs as "cytoplasmic rRNAs". And it would also make sense to define these terms as "functioning in the cytoplasm" (primarily), rather than following the pattern for the proposed organellar/plastid defs above and define them as "derived from the genome of the nucleus" (which would prohibit usage for prokaryotic rRNAs).

So, from that point of view, and looking at the current def of "rRNA (SO:0000252)" (_RNA that comprises part of a ribosome, and that can provide both structural scaffolding and catalytic activity_), I'd suggest new/changed defs along these lines:

**name: cytoplasmic_rRNA**
def: "rRNA (SO:0000252) that comprises part of a cytoplasmic ribosome, derived from the nuclear genome in eukaryotes."

**name: organellar_rRNA**
def: "rRNA (SO:0000252) that derives from the genome of an organelle rather than from the nucleus of a cell." [PMID:3044395]
>
def: "rRNA (SO:0000252) that derives from an organelle genome and comprises part of a ribosome in that organelle." [PMID:3044395]

**name: mt_rRNA**
def: "Mitochondrial ribosomal RNA." [GENCODE:http://www.gencodegenes.org/gencode_biotypes.html]
>
def: "rRNA (SO:0000252) that derives from a mitochondrial genome and comprises part of a mitochondrial ribosome.

**name: plastid_rRNA**
def: "rRNA transcribed from the genome of a plastid such as a chloroplast." [PMID:3044395, PMID: 24572720]
>
def: "rRNA (SO:0000252) that derives from the genome of a plastid (such as a chloroplast) and comprises part of a plastid ribosome." [PMID:3044395, PMID: 24572720]

**Comment by davidwsant** [comment]
I appreciate that all of you have weighed in on this. 

Thanks for pointing out the typo. I admit, I make lots of typos and I appreciate it when other people catch them. 

It looks like I forgot to copy over my notes for a proposed new term cytoplasmic rRNA, as Anton suggested. Here is what I currently have for that term:

name:   cytoplasmic_rRNA
def: "rRNA (SO:0000252) comprises part of a cytoplasmic ribosome. " [PMID:3044395]
synonym: "cytoplasmic rRNA" EXACT []
synonym: "cytoplasmic ribosomal RNA" EXACT []
is_a: SO:0000252 ! rRNA

I don't think we even need to mention that it comes from the nuclear genome in eukaryotes. Do you guys think that part is important? 

As for small_subunit_rRNA and large_subunit_rRNA, do you think we should just make the child terms have a second is_a relationship to cytoplasmic_rRNA, mt_rRNA or plastid_rRNA? I have made a powerpoint picture to show how I think this setup would be. The circle is just to group all of the large_subunit_rRNA children together because including all of the arrows made it too noisy. 

[Ribosomal RNA structure.pptx](https://github.com/The-Sequence-Ontology/SO-Ontologies/files/6393968/Ribosomal.RNA.structure.pptx)

What do you guys think of this setup?

**Comment by sjm41** [comment]
_I don't think we even need to mention that it comes from the nuclear genome in eukaryotes. Do you guys think that part is important?_
Not important - happy to drop that.

I like your ppt suggestion - works for me!

**Comment by AntonPetrov** [comment]
I like the ppt too - thank you!

> As for small_subunit_rRNA and large_subunit_rRNA, do you think we should just make the child terms have a second is_a relationship to cytoplasmic_rRNA, mt_rRNA or plastid_rRNA?

I think this is a good idea ☝️. If I understand it correctly, this will make it clear that a 5S rRNA can be in cytoplasm, or mitochondria, or plastids, which makes sense.

Many thanks for looking into this, it will be very useful for us at RNAcentral!

Also, I agree with name changes proposed by Steven @sjm41

**Comment by davidwsant** [comment]
Thank you guys for looking over this. I actually think there is a problem with the setup. I didn't realize that 5S rRNA was in cytoplasmic ribosomes as well as mitochondrial ribosomes. If it is, then I don't want to include an is_a to cytoplasmic_rRNA. Instances of 5S mitochondrial rRNA would then be annotated with both rRNA_5_S and with mitochondrial_large_subunit_rRNA while instances of cytoplasmic rRNA would be annotated with both rRNA_5_S and cytoplasmic_rRNA. Is this correct? Are any of the other rRNA subtypes found in both cytoplasmic rRNA and in organellar rRNA?
[Current SO rRNA](http://sequenceontology.org/browser/current_release/term/SO:0000651):
- rRNA_5_8_S
- rRNA_28_S
- rRNA_2_S
- rRNA_21_S
- rRNA_5_S
- rRNA_25_S
- rRNA_23_S

Thanks,

Dave

**Comment by sjm41** [comment]
Hi Dave

I didn't know about the 5S rRNA in mitochondria....

Seems mammalian mitoribosomes were thought to contain 5S (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC25503/ https://pubmed.ncbi.nlm.nih.gov/21685364/), but that was subsequently disproved (e.g. https://www.pnas.org/content/113/43/12198)

But seems 5S rRNA is present in mitoribosomes of plants and protozoa, **and of plastid ribosomes**:
https://en.wikipedia.org/wiki/5S_ribosomal_RNA#Presence_in_organelle_ribosomes
https://ec.asm.org/content/9/5/762

What's unclear to me is whether there is a _distinct_ 5S rRNA species (encoded by the mito/plastid genome) that is incorporated into those ribosomes, or if it's the _same_ 5S rRNA as being used in cytoribosomes (encoded by the nuclear genome).  If they are distinct, then we can deal with that within the structure proposed in your ppt by having 2 distinct 5S rRNA entries with different parentage.  Need to do some more reading....

@AntonPetrov - are there examples of the mito/plastid 5S rRNA in RNAcentral?  Can we ask the rRNA experts in the RNAcentral consortium about this?

**Comment by davidwsant** [comment]
Thanks for looking into this a little further for me. In that case, I think the structure in the powerpoint is still correct.

Here is what I have for the definitions and relationships of new terms. Sorry about the double spaces, those are an artifact of the way I copied and pasted. 

id: new
name:   cytoplasmic_rRNA
def: "rRNA (SO:0000252) that   localizes to the cytoplasm of the cell. This includes small_subunit_rRNA   (SO:0000650) and large_subunit_rRNA (0000651)." [PMID:3044395]
synonym: "cytoplasmic rRNA"   EXACT []
synonym: "cytoplasmic ribosomal   RNA" EXACT []
is_a: SO:0000252 ! rRNA

id: SO:new
name: organellar_rRNA
def: "rRNA (SO:0000252) that derives  from an organelle genome and comprises part of a ribosome in that organelle." [PMID:3044395]
synonym: "organellar rRNA" EXACT []
synonym: "organellar ribosomal RNA" EXACT []
is_a: SO:0000252 ! rRNA

id: SO:0002128
name: mt_rRNA
def: "rRNA (SO:0000252) that derives from a mitochondrial genome and comprises part of a   mitochondrial ribosome."   [GENCODE:http\://www.gencodegenes.org/gencode_biotypes.html]
synonym: "mitochondrial_rRNA" EXACT []
synonym: "Mt_rRNA" EXACT []
is_a: SO:new! organellar_rRNA

id: SO:new
name: plastid_rRNA
def: "rRNA (SO:0000252) that derives from the genome of a plastid (such as a chloroplast) and comprises part of a plastid ribosome." [PMID:3044395, PMID: 24572720]
synonym: "plastid rRNA" EXACT []
is_a: SO:new !  organellar_rRNA

id: SO:new
name: mitochondrial_small_subunit_rRNA
def: "mitochondrial rRNA (SO:0002128) transcripts that are structures of the small subunit of mitochondrial RNA." [PMID:3044395, PMID: 24572720]
synonym: "mitochondrial small subunit rRNA" EXACT []
is_a: SO:0002128 ! mt_rRNA
is_a: SO:0000650 !   small_subunit_rRNA

id: SO:new
name: mitochondrial_large_subunit_rRNA
def: "mitochondrial rRNA  (SO:0002128) transcripts that are structures of the large subunit of  mitochondrial RNA." [PMID:3044395, PMID: 24572720]
synonym: "mitochondrial large subunit rRNA" EXACT []
is_a: SO:0002128 ! mt_rRNA
is_a: SO:0000651 ! large_subunit_rRNA

id: SO:new
name: plastid_small_subunit_rRNA
def: "plastid rRNA (SO:0002347)  transcripts that are structures of the small subunit of RNA of a plastid such as a chloroplast." [PMID:3044395, PMID: 24572720]
synonym: "plastid small subunit rRNA" EXACT []
is_a: SO:new! plastid_rRNA
is_a: SO:0000650 !  small_subunit_rRNA

id: SO:new
name: plastid_large_subunit_rRNA
def: "plastid rRNA (SO:0002347)  transcripts that are structures of the large subunit of RNA of a plastid such as a chloroplast." [PMID:3044395, PMID: 24572720]
synonym: "plastid small large rRNA" EXACT []
is_a: SO:new! plastid_rRNA
is_a: SO:0000651 !  large_subunit_rRNA


In addition to these new terms, I will add "is_a: SO:new! cytoplasmic_rRNA" relationships to these terms:
- rRNA_16_S (SO:0001000)
- rRNA_18_S (SO:0000407)
- rRNA_5_8_S (SO:0000375)
- rRNA_28_S (SO:0000653)
- rRNA_2_S (SO:0002337)
- rRNA_21_S (SO:0001171)
- rRNA_5_S (SO:0000652)
- rRNA_25_S (SO:0001002)
- rRNA_23_S (SO:0001001)

Does this all look correct? Do you have any requests for changes to these definitions or names? 

Best,

Dave

**Comment by AntonPetrov** [comment]
@sjm41 Good points about the mito-5S taxonomic distribution. This 5S has distinct structural features and has to be modelled by a specialised Rfam family ([RF02547](https://rfam.org/family/RF02547)). It is encoded in the mito-genomes, but not all of them, as you pointed out.

Let's ask @aspetr01 - Anton, does the following diagram make sense to you? As you can see from this long thread we are trying to revisit the [rRNA subtree](http://sequenceontology.org/browser/current_release/term/SO:0000252) in Sequence Ontology. Any input will be greatly appreciated!

I am copying the image from the Powerpoint by @davidwsant below for ease of reference:
<img width="1007" alt="Screenshot 2021-05-03 at 20 41 20" src="https://user-images.githubusercontent.com/432675/116924560-ee93f580-ac4f-11eb-96cd-863ec1378f5f.png">

**Comment by sjm41** [comment]
@davidwsant said:
 _In that case, I think the structure in the powerpoint is still correct._

I think @AntonPetrov is confirming that there are two different types of 5S rRNA - the 'regular' 5S rRNA that is part of large subunit of cytoribosomes, and a distinct 5S rRNA that is part of (some) mitochondrial and plastid ribosomes. If we're going to keep the current rRNA_5S (SO:0000652) term to refer solely to the cyto form, then don't we need a new term (with different parentage) for the mito/plastid 5S rRNA?

I also noticed the parentage for "rRNA_21S" will need changing from 'cytoplasmic rRNA' to 'mt_RNA' (def could be improved too):

**rRNA_21S (SO:0001171 )
A component of the large ribosomal subunit in mitochondrial rRNA.**

**Comment by davidwsant** [comment]
Yes, rRNA_21S will need to be moved. 

![image](https://user-images.githubusercontent.com/46572856/117032799-05256580-acbf-11eb-8975-c909ae9f67bc.png)

I think a better parent for rRNA_21S would be mitochondrial_large_subunit_rRNA. What new definition would you suggest?

As for the rRNA_5S, if we want to discuss the mito/plastid ribosomes then we should perhaps change the name to cytoplasmic_5S_rRNA, but keep the definition the same. No one has ever asked for a 5S rRNA for plastid or mitochondria specifically in the past. The wiki page references look like they are mostly about Amoeba. I don't know that it is necessary to add a term that is unlikely to be used. If we do add terms for these, I am thinking we would name them "mitochondrial_5S_rRNA" and "plastid_5S_rRNA", and include information about how they are found in plants, along with the references that @sjm41 included above. I think we will need a few more peer reviewed publications if we want to add these terms. 

@AntonPetrov, @keilbeck what is your take on this? 

-Dave

**Comment by sjm41** [comment]
Hi @davidwsant 

**_I think a better parent for rRNA_21S would be mitochondrial_large_subunit_rRNA._**
Ah yes, I'd overlooked that the new "mitochondrial_large_subunit_rRNA" term is a general grouping term rather than a specific term for the 16S LSU mito rRNA...
If we make rRNA_21S a specific child of mitochondrial_large_subunit_rRNA, then it would make sense to also have rRNA_16S as a second specific child term.
Then, it would also make sense to include the mito-specific 5S rRNA as a third child term of mitochondrial_large_subunit_rRNA.  I think these should all have 'mitochrondrial in the name' to clearly distinguish them (as you already suggest for the 5S):
mitochondrial_21S_rRNA
mitochondrial_16S_rRNA
mitochondrial_5S_rRNA
Making these children of "mitochondrial_large_subunit_rRNA" means they won't need "large_subunit_rRNA" as a second parent.

I believe there's only one small subunit mito rRNA (https://www.nature.com/articles/srep04089 - is that right @AntonPetrov ? @aspetr01 ?), so maybe "mitochondrial_small_subunit_rRNA" could/should just become "mitochondrial_12S_rRNA", or else keep the current name and state the size in the definition.

I can't easily find info on the composition and sizes of plastid rRNAs - some limited info available for chloroplasts, but whether that applies to all plastids is unclear to me.  So maybe best to leave the plastid rRNAs as just "plastid_small_subunit_rRNA" and "plastid_large_subunit_rRNA".


**_What new definition would you suggest [for rRNA_21S]?_**
Current def is "A component of the large ribosomal subunit in mitochondrial rRNA.", which doesn't really make sense.
How about:  "A component of the large ribosomal subunit in yeast mitochondria. (PMID:11867542)"


**_As for the rRNA_5S, if we want to discuss the mito/plastid ribosomes then we should perhaps change the name to cytoplasmic_5S_rRNA, but keep the definition the same._**
Yep!




Also, here's another good reference for the mito/plastid 5S rRNAs:
https://pubmed.ncbi.nlm.nih.gov/25429974/

**Comment by sjm41** [comment]
Hi @davidwsant , @AntonPetrov 

Did my previous comment make sense?  Can we move forward with implementing these changes?
Cheers
Steven.

**Comment by AntonPetrov** [comment]
Sorry for the delay. As suggested by @aspetr01 over email, the use of sedimentation constants (16S, 18S etc) is not great because in many species like _D. melanogaster_ the rRNAs are fragmented, but the reliance on molecule size in the current SO classification implies that the ribosomal subunits are made of continuous sequences. 

I am not advocating the removal or renaming of the existing terms because they are widely used, just pointing out that they only apply to the non-fragmented rRNAs and it might be a good idea to refrain from adding more terms with sedimentation constants.

As long as the [updated tree](https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/493#issuecomment-832073096) includes a consistent set of large and small subunits for organelles and non-organelles (which it does), I will be very happy with the changes.

**Comment by davidwsant** [comment]
Hi @sjm41,

You mentioned moving the rRNA_16S to mitochondrial_large_subunit_rRNA. Everything I have looked at suggests that this functions as the small subunit. This is present in bacteria and archaea, which would fall under "cytoplasmic rRNA". I think rather than changing the name of rRNA_16S and adding a second term, it might be better to add a child term 'mitochondrial_16S_rRNA' that would have parents rRNA_16S and mitochondrial_small_subunit_rRNA. How does that sound? 
I think that might be a good call for the rRNA_5_S as well. As far as I can tell, 21S rRNA is only in mitochondria, so it will therefore not need a parent term that is not mitochondrial. 

The reason I want to make child terms rather than changing the name of a term and adding another sister term is that these terms are already in use, and changing 'rRNA_5S' to 'cytoplasmic_5S_rRNA' would make any instances currently using this term for mitochondrial 5S rRNA incorrect. The same would go for the 16S. Adding a child term allows us to add a new level of specificity, but will not make other annotations using the existing terms incorrect. If plastid or cytoplasmic 5s rRNA are specifically requested later we can add them, but the other terms are in use and will remain correct for those instances. Here is the new layout if we things this way:

![image](https://user-images.githubusercontent.com/46572856/118894488-94d33280-b8c1-11eb-882d-d48a44e2b46c.png)

As for the new definition that you are proposing for 21S rRNA, it states that 21S rRNA is only in yeast mitochondria. Is that correct? If so, then we should update the definition as suggested. 

How does this look overall? 

Dave

**Comment by sjm41** [comment]
Thanks @AntonPetrov , @davidwsant . This is all trickier than it looked at first....  I'm afraid I've several points to make....would it be easier to arrange a video call to discuss?


1. Regarding the new definition of 'rRNA_21_S' - all the references I can find for this say that it's a yeast mitochondrial rRNA, so I think my suggested def ("A component of the large ribosomal subunit in yeast mitochondria. (PMID:11867542)") is accurate. Could also add PMID: 28154081 as another reference.

2. Wrt your 16S rRNA query - I wasn't suggesting changing the name/parentage of the _current_ 'rRNA_16S (SO:0000650)' term, which as you say is the prokaryotic small subunit rRNA.  I was saying that because (i) the existing 'rRNA_21_S' (SO:0001171) is being moved to be a child of 'mitochondrial_large_subunit_rRNA', and (ii) we had decided there was a need for a new distinct 'mitochondrial_5S_rRNA' term, then it would make sense to also instantiate a **new** sister term for the regular metazoan mitochondrial large rRNA, i.e. 'mitochondrial_16S_rRNA'. (Apologies for being unclear!)

3. Regarding those two new 'mitochondrial_5S_rRNA' and 'mitochondrial_16S_rRNA' terms - there seems to be a couple of conflicts in the latest proposed structure in that they are currently asserted to be both 'mt_rRNA' and 'cytoplasmic_rRNA' via their parentage.

4. If we have specific children of 'mitochondrial_large_subunit_rRNA', it would make sense to instantiate "mitochondrial_12S_rRNA" (the 'regular' eukaryotic small mito rRNA) and also "mitochondrial_15S_rRNA" (which I see is the yeast version - PMID:11867542 & 28154081) as children of 'mitochondrial_small_subunit_rRNA'.

5. The alternative to doing points 1-4, following up on Anton's comment, would be to not to make any of these new specific terms and just have "mitochondrial_large_subunit_rRNA" and "mitochondrial_small_subunit_rRNA". In that case, the existing 'rRNA_21_S' term should be obsoleted (or merged into "mitochondrial_large_subunit_rRNA").

6. Regarding possible usage of the existing 'rRNA_5S' or 'rRNA_16_S' terms to annotate the mitochondrial forms - the definitions of 'rRNA_5S' ("a component of the large ribosomal subunit in both prokaryotes and eukaryotes.") and 'rRNA_16_S' ("A large polynucleotide in Bacteria and Archaea, which functions as the small subunit of the ribosome.") indicate that these refer to the 'regular', non-mitochondrial forms of these rRNAs, so I don't think that should be a concern.

7. Looking again at the overall proposed structure and Anton's original request - I don't think the proposed structure allows straightforward identification of large or small subunit cytoplasmic rRNAs, does it?  You'd have to find the **intersection** of terms annotated to 'cytoplasmic rRNA' and 'large_subunit_rRNA' (or 'small_subunit_rRNA').  I wonder whether a simpler structure would work better (pasted below) - it just makes a single primary separation of cytoplasmic versus organellar rRNAs, and doesn't attempt an orthogonal primary classification of large vs small subunits.  (The new terms we're considering are shown with a red border.) Thoughts?

![Screenshot 2021-05-20 at 12 03 48](https://user-images.githubusercontent.com/16306861/118968170-7e7db300-b963-11eb-8ca3-fddd77d42fbe.png)

[Ribosomal.RNA.structure-SM.pptx](https://github.com/The-Sequence-Ontology/SO-Ontologies/files/6515333/Ribosomal.RNA.structure-SM.pptx)

**Comment by billslab** [comment]
I think you are right and that we should have a zoom meeting to discuss. 
@sjm41 and @AntonPetrov, are you guys both in the UK? I am in Utah, MDT time zone throughout the summer. It looks like I am 7 hours behind you guys. If we meet at 09:00h MDT/16:00h BST (or 30 minutes before that time) it should be during the work day for both groups. I am busy at that time on Monday and Wednesday next week, but should be available the other days. I can set up a zoom meeting if we can find a time. 

Best,

Dave

**Comment by sjm41** [comment]
I’m available at 4pm UK time on Thursday or Friday next week - slight preference for Thursday.

Cheers,
Steven.

On 20 May 2021, at 21:38, billslab ***@***.******@***.***>> wrote:



I think you are right and that we should have a zoom meeting to discuss.
@sjm41<https://github.com/sjm41> and @AntonPetrov<https://github.com/AntonPetrov>, are you guys both in the UK? I am in Utah, MDT time zone throughout the summer. It looks like I am 7 hours behind you guys. If we meet at 09:00h MDT/16:00h BST (or 30 minutes before that time) it should be during the work day for both groups. I am busy at that time on Monday and Wednesday next week, but should be available the other days. I can set up a zoom meeting if we can find a time.

Best,

Dave

**Comment by AntonPetrov** [comment]
Both times suggested by @sjm41 work for me as well - it will indeed be easier to discuss during a call.

I like Steven's version as it's very streamlined and logical but I see @davidwsant point about the danger of renaming such old terms. Look forward to our discussion!

**Comment by davidwsant** [comment]
Let's plan on Thursday. I will send a zoom invite via email.

--Dave

**Comment by davidwsant** [comment]
Hi all,

Thank you for your several comments and for even meeting through zoom to go over all of the changes. Definitions have been updated to have a similar structure for all definitions (special thank you to Steven Marygold). New terms have been added to distinguish rRNA from genomes of organelles vs the nuclear genome. Commit 9f923ba has been pushed to GitHub. The [SO Browser](http://sequenceontology.org/browser/obob.cgi) should reflect these changes within 24 hours. GitHub Issue #513 will address the issue of the rRNA genes that mirror these terms. 

Best,

Dave Sant

**Comment by sjm41** [comment]
Many thanks to you David for your patience and time with this!
