### ISSUE TITLE
Terms related to functional effect of a variant from Gene Curation Coalition (GenCC)

### ISSUE THREAD

**Issue by davidwsant** [The-Sequence-Ontology/SO-Ontologies#501]
I received an email this week about some new terms from the National Heart and Lung Institute. Below I will copy the entire email along with how I think this will be filled in. 
Dear SO,
 
I'm leading the effort James mentioned below to develop a standard ontology for disease curation.  We now have a finalised framework for this and a list of agreed terms for variant classes based on SO terms.  Essentially we have added child terms to capture more granularity where that will impact functional consequence e.g. if a nonsense variant is predicted to undergo or escape nonsense mediated decay it will have a very consequence.  We link these in a matrix to 6 high level consequence terms to record the most likely effects:
* Altered gene product level
  * Unspecified change in  gene product level
  * Increased gene product level
  * Reduced gene product level
    * Decreased gene product level
    * Absent gene product
* Altered gene product structure
* No effect
 
 
Could I run our proposed SO terms past you?  I've copied our list below with the proposed child terms in brackets.  It would be great if we could arrange a video conference to get your thoughts and see if these could be formalised as SO terms.
 
Kind regards
Ang
 
Angharad Roberts 
Clinical Research Fellow
Cardiovascular Genetics and Genomics
National Heart and Lung Institute
Imperial College London

**What is this request referring to?**
All of these will be under [functional_effect_variant SO:0001536](http://www.sequenceontology.org/browser/current_svn/term/SO:0001536), with a nested structure

**What is the name you would like SO to give the term?**
The name of the term SO can use. Note, if you include spaces they will be replaced with underscores. Example: rRNA_gene

**What is the definition that you would like for this term?**
My guess is that half of these will be synonyms of current terms, but the ones listed are 'Altered gene product level', 'Unspecified change in gene product level', 'Increased gene product level', 'Reduced gene product level', 'Decreased gene product level', 'Absent gene product level', 'Altered gene product structure' and 'No effect'.

**Synonyms**
These will be discussed further

**Parent Term**
[functional_effect_variant SO:0001536](http://www.sequenceontology.org/browser/current_svn/term/SO:0001536)

**Relevant Publications**
No specific publications were provided, but the terms they have provided are descriptive.

**Comment by davidwsant** [comment]
Hi Ang, 

Thank you for bringing these terms to our attention. At first glance I thought that most of these terms were already present in SO, but upon further investigation I found that only one of them has a term that is already sufficient, No Effect.

I believe the No effect term can be fulfilled by the current SO term [functionally_normal SO:0002219](http://sequenceontology.org/browser/current_svn/term/SO:0002219). This term was added last year, and we had a discussion about using the term 'no effect'. In the end we chose not to add the term 'no effect' because although it has no effect on the gene product, SO covers nucleotide sequences and the variant does not have 'no effect' on the DNA sequence. We can discuss this further, but I still believe adding a synonym 'no effect' would be misleading for SO.

The branch of Altered gene product does not appear to be present in SO, so all child terms here would need to be added. I am thinking this:


name:   altered_gene_product_level
def: "A sequence variant that alters   the level of transcription of a gene." 
synonym:   "altered gene product level" EXACT []
synonym: "altered transcription   level" EXACT []
synonym:   "altered_transcription_level" EXACT []
is_a: SO:0002218 ! functionally_abnormal


name:   increased_gene_product_level
def: "A sequence variant that   increases the level of transcription of a gene." 
synonym: "increased gene product   level" EXACT []
synonym: "increased transcription   level" EXACT []
synonym:   "increased_transcription_level" EXACT []
is_a: SO:0002314 !   altered_gene_product_level


name:   reduced_gene_product_level
def: "A sequence variant that   decreases the level of transcription of a gene." 
synonym: "reduced gene product   level" EXACT []
synonym: "reduced transcription   level" EXACT []
synonym:   "reduced_transcription_level" EXACT []
is_a: SO:0002314 !   altered_gene_product_level


name:   absent_gene_product
def: "A sequence variant that   entirely stops the transcription of a gene." 
synonym: "absent gene product"   EXACT []
is_a: SO:0002316 !   reduced_gene_product_level
is_a: SO:0002055 ! null_mutation

This leaves out two terms: Unspecified change in gene product level and decreased gene product level. I do not think either of these terms are necessary. 
Typically, in an ontology if you do not know which of the child terms to use, the parent is typically used. For this instance, if you know it alters gene product level but do not know if it increases or decreases the product level, you would use the term 'altered_gene_product_level' instead of making a term that states that you do not know if it is increased or decreased.
As for the decreased gene product level, this would be covered by 'reduced_gene_product_level'. If it is lowered but not stopped, you would use 'reduced_gene_product_level'. If it is stopped then it is lowered to the point of zero transcription, so it would need the new term 'absent_gene_product'. The term 'absent_gene_product' is also a type of 'null_mutation', so I have added that relationship as well. 

One more thing that needs to be covered here - I put all of these under 'functionally_abnormal' rather than SO:0001536 functional_effect_variant. I think this is the correct choice, but I would like your input on that. 

The final term mentioned that needs to be added is altered gene product structure:

name: altered_gene_product_structure
def: "A sequence variant that alters the structure of a gene." 
synonym: "altered gene product structure" EXACT []
is_a: SO:0002218 ! functionally_abnormal

This one can then get further child terms such as splice variants and premature stop codons that do not lead to nonsense mediated decay. 

How do these proposed term names and definitions sound?

Thanks,

Dave Sant

**Comment by angharadroberts** [comment]
Hi Dave,
 
I think we are on the same track with just a few areas to clarify.  I’ve tried to cover them here, but we would be happy to jump on a call if useful (our timezone is GMT).
 
1. We agree “no effect” is essentially synonymous to and can be fulfilled by functionally_normal SO:0002219
 
2.  We agree our nested terms below do contain some redundancy:

- Altered gene product level 
    - Unspecified change in  gene product level
    - Increased gene product level
    - Reduced gene product level 
           - Decreased gene product level
           - Absent gene product

We aren’t familiar with your notations ‘is_a’ and ‘!’,  and we’re not quite clear how your proposal would be arranged hierarchically but I think we are on the same page:
We agree ‘Unspecified change in  gene product level’ is essentially redundant as the parent term can be used.  However I wonder if  function_uncertain_variant SO:0002220  is somewhat equivalent and might be useful to highlight those variants where it is very difficult to predict the effect eg some splice variants.  Would be interested in your thoughts.
We agree only one of ‘Reduced gene product level’ or ‘Decreased gene product level’ is needed.  We feel ‘decreased’ is the more intuitive opposite of ‘increased’ and would prefer to use ‘decreased’ rather than ‘reduced’. 
Would ‘Absent gene product’ be a child term of ‘Decreased gene product’?
 
As we understand it the new hierarchy would be:
- Altered gene product level 
    - Increased gene product level
    - Decreased gene product level
        - Absent gene product

I’m not quite sure about the definitions you proposed.  That would be helpful to discuss as we want to cover all mechanisms that lead to an alteration of gene product level: not just the level or rate of transcription but also for example level or rate of translation due to various mechanisms.
 
3.    It would be helpful to discuss further whether these are positioned as children of 'functionally_abnormal' vs ‘functional_effect_variant’. 
I note the hierarchy:
        sequence_variant
              functional_effect_variant
              function_uncertain_variant
              functionally_abnormal
              functionally_normal
If we did include function_uncertain_variant as a child of ‘Altered gene product level’ then it would perhaps make sense to put everything under ‘functional_effect_variant’.
 
I found the terms within transcript_function_variant and translational_product_function_variant somewhat confusing and they almost seemed overlapping so if we did position our terms within ‘functionally_abnormal’ it would benefit from discussion with you regarding how they sit alongside transcript_function_variant and translational_product_function_variant.
                Eg:
transcript_function_variant (SO:0001538) A sequence variant which alters the functioning of a transcript with respect to a reference sequence
     -  translational_product_level_variant (SO:0001553)). 
                  -  decreased_translational_product_level SO:0001555 A sequence variant which decreases the translational product level with respect to a reference sequence (child of translational_product_level_variant (SO:0001553)). 

translational_product_function_variant (SO:0001539)  A sequence variant that affects the functioning of a translational product with respect to a reference sequence.
     -   level_of_transcript_variant (SO:0001540)
                 -  decreased_transcript_level_variant (SO: 0001541) A sequence variant that decreases the level of mature, spliced and processed RNA with respect to a reference sequence.


4. For the final term altered_gene_product_structure this does not change the structure of the gene but rather is a sequence variant that alters the gene product, be that a protein, miRNA etc.  eg a missense variant that leads to a misfolded protein or a splice variant that leads to exon skipping.  I haven’t found a pre-existing high level SO term for this. 
We agree this would then take further child terms such as splice variants and premature stop codons that do not lead to nonsense mediated decay.
 
5.  We are also keen that any variant leading to a prematurely truncated protein (including frameshift and splice variants etc)  have 2 child terms to distinguish whether it is predicted to undergo or escape nonsense mediated decay as this has implications for inferring the consequence and clinical interpretation of these variants.  I found the following terms but I thinkthey don’t quite capture what we want.  I *think* they refer to the transcript rather than the consequence of the specific variant:
NSD_transcript
NMD_transcript 
NMD transcript variant

Eg my understanding of NMD_transcript_variant is any variant in a transcript susceptible to nonsense mediated decay.  Whereas we aim to specify if a given variant is predicted to lead to or escape NMD based on it’s position relative to the C terminus.
 
6. We had also identified some possible refinements to predictable UTR consequences and will link in with Nicky Whiffin who has been working on this.
 
7.  We are liaising with interested parties regarding what CNV or structural variants to capture and to identify corresponding SO terms eg exon_loss_variant SO:http://www.sequenceontology.org/browser/current_svn/term/SO:0001572 and may revert to you in due course. 
 
Looking forward to your thoughts on it, I’ll copy this into the github thread but would appreciate email too!
Ang

**Comment by davidwsant** [comment]
Hi Ang,

I apologize, I thought I had sent a direct email back to you, but I also thought I had posted this in the Issue thread and apparently that didn't happen. This semester has been incredibly busy for me, but I hope to be able to add this. 

The terms 'is_a' and the '!' are actually referring to the OBO format that is used for editing the files. 'is_a' literally means 'is a' and all terms have an is_a relationship. The '!' simply is part of the text to divide the ID and the name for the ID in OBO format. I apologize that I did not explain that before. 

I agree that function_uncertain_variant (SO:0002220) would be helpful for terms where you are unsure if it changes the product. Splice examples are exactly what we had in mind when it was created. I had originally thought of posting about this, but it does not really overlap with any of the terms that you had proposed so I chose not to. I do think it is important in addition to the terms proposed, just not in place of any term proposed. 

I have changed the term in my notes to decreased_gene_product_level from reduced_gene_product_level, I agree with your reasoning. 

I do like the structure that you have proposed here where absent gene product is a child of decreased. Absent is indeed decreased, just so far that it is absent. 

As for the functional_effect_variant, I do think it might be a good idea to set up a call to discuss this. However, my schedule is extremely full currently and I will probably not be available until the second week of December. You can send me direct emails to set this up. For now I will point out that the structure is as follows:
* sequence_variant
  * functional_effect_variant
    * function_uncertain_variant
    * functionally_abnormal
    * functionally_normal

functional_effect_variant simply refers to when the function of a variant is measured with respect to the reference. The official definition is "A variant whereby the effect is evaluated with respect to a reference." This term was created to allow us to group all of these terms about funding functional consequences together. SO actually doesn't really cover functional effects and most are covered by Gene Ontology, so we created this term so that there could be a parent term for all annotations of judging the functional consequences of a variant. 

Function_uncertain_variant would not fit well a child of altered_gene_product_level. The definition is "A sequence variant in which the function of a gene product is unknown with respect to a reference" and could refer to things where you are uncertain if the actual product is changed rather than the product level. The example you used with splicing is a perfect example. Splicing would change the product, not the product level. 

As for discussing transcript_function_variant and translational_product_function_variant, I think this may be stepping into bounds of needing to have a call. I will set a reminder in my calendar and reach out to you in December to go over this more thoroughly. 

Thanks,

Dave

**Comment by davidwsant** [comment]
[New Variant Function Terms.pptx](https://github.com/The-Sequence-Ontology/SO-Ontologies/files/5697868/New.Variant.Function.Terms.pptx)
[New Variant Term Definitions.xlsx](https://github.com/The-Sequence-Ontology/SO-Ontologies/files/5697869/New.Variant.Term.Definitions.xlsx)
Hi guys,

I have made an Excel spreadsheet with the definitions and such, as well as a powerpoint that contains a diagram of how this would be represented. Ang and James, please review the structure and the definitions of the terms before I add them to the SO.  

Thanks,
Dave

The contents of the Excel document are also copied here to the comment:


[Term]
id: New Term
name: altered_gene_product_structure
def: "A sequence variant that alters   the structure of a gene."
synonym: "altered gene product   structure" EXACT []
is_a: SO:0001536 !   functional_effect_variant

[Term]
id: New Term
name: altered_gene_product_level
def: "A sequence variant that alters   the level of transcription of a gene."
synonym: "altered gene product   level" EXACT []
synonym: "altered transcription   level" EXACT []
synonym:   "altered_transcription_level" EXACT []
is_a: SO:0001536 !   functional_effect_variant
 
[Term]
id: New Term
name: decreased_gene_product_level
def: "A sequence variant that   decreases the level of transcription of a gene."
synonym: "decreased gene product   level" EXACT []
synonym: "decreased transcription   level" EXACT []
synonym:   "decreased_transcription_level" EXACT []
synonym:   "reduced_gene_product_level" EXACT []
synonym: "reduced gene product   level" EXACT []
synonym: "reduced transcription   level" EXACT []
synonym:   "reduced_transcription_level" EXACT []
is_a: SO:New Term !   altered_gene_product_level

[Term]
id: New Term
name: absent_gene_product
def: "A sequence variant that   entirely stops the transcription of a gene."
synonym: "absent gene product"   EXACT []
is_a: SO:New Term !   decreased_gene_product_level
is_a: SO:0002055 ! null_mutation

[Term]
id: New Term
name: increased_gene_product_level
def: "A sequence variant that   increases the level of transcription of a gene."
synonym: "increased gene product   level" EXACT []
synonym: "increased transcription   level" EXACT []
synonym:   "increased_transcription_level" EXACT []
is_a: SO:New Term !   altered_gene_product_level

**Comment by davidwsant** [comment]
Hi Ang and James,

I have added the terms discussed. They have been given the ID's SO:0002314-SO:0002318. They have been pushed to GitHub. These terms will be visible in the [SO Browser](http://www.sequenceontology.org/browser/obob.cgi) within about 24 hours. I will add the other terms discussed (#521) soon.

Best,

Dave
