### ISSUE TITLE
Need citation for "found in archaea" in SO:0000375

### ISSUE THREAD

**Issue by Artoria2e5** [The-Sequence-Ontology/SO-Ontologies#505]
**What is the SO term name and accession?**
rRNA_5_8S (SO:0000375)

**Describe what you would like to change.**
The definition ends in "5_8S rRNA is also found in archaea", but I am yet to found any citation that claims so. It appears that this sentence originated, uncited, in the Stockholm data for Rfam and somehow made it here. I am requesting an explanation of this sentence.

**Relevant Publications**
Wouldn't be asking if I had one claiming so.

**Comment by davidwsant** [comment]
Hi Mingye,

I think you are correct in pointing out that 5.8S rRNA is not in Archaea. I think when this term was created Archaea was listed because it is mentioned in the Wikipedia link and the Sanger institute link, but those articles did no state that Archaea contains 5.8S rRNA. This sentence has been removed from the definition.

Thanks,

Dave
