### ISSUE TITLE
NTR: sncRNA_gene

### ISSUE THREAD

**Issue by sjm41** [The-Sequence-Ontology/SO-Ontologies#514]
Under 'ncRNA', there is a 'sncRNA' (small non-coding RNA, def: "A non-coding RNA less than 200 nucleotides in length.") term that usefully groups the following:
- small_regulatory_ncRNA (includes miRNA, piRNA, tmRNA)
- snRNA
- snoRNA
- tRNA

For consistency, can you make a similar 'sncRNA_gene' term to group the equivalent gene terms under 'ncRNA_gene'?
- miRNA_gene
- piRNA_gene
- snRNA_gene
- snoRNA_gene
- tRNA_gene
- tmRNA_gene

===

**What is this request referring to?**
small non-coding RNA gene

**What is the name you would like SO to give the term?**
sncRNA_gene

**What is the definition that you would like for this term?**
A gene encoding a ncRNA less than 200 nucleotides in length.

**Synonyms**
small non-coding RNA gene

**Parent Term**
ncRNA_gene (SO_0001263)

**Relevant Publications**
https://pubmed.ncbi.nlm.nih.gov/30069443/
https://pubmed.ncbi.nlm.nih.gov/28449079/
https://pubmed.ncbi.nlm.nih.gov/30937442/

**Comment by davidwsant** [comment]
Hi @sjm41,

I have created a new term: 


id: SO:0002342
name: sncRNA_gene
def: "A ncRNA_gene (SO:0001263) that   is less than 200 nucleotides in length." [PMID:30069443, PMID:28449079,   PMID:30937442]
synonym: "sncRNA gene" EXACT []
synonym: "small non-coding RNA   gene" EXACT []
is_a: SO:0001263 ! ncRNA_gene

I have moved the following terms so that they are now children of sncRNA_gene. 

- miRNA_gene
- piRNA_gene
- snRNA_gene
- snoRNA_gene
- tRNA_gene
- tmRNA_gene

This should be visible on the SO Browser within the next 24 hours.

Best,

Dave

**Comment by sjm41** [comment]
Great, thanks Dave.
