### ISSUE TITLE
Update definitions for decreased_gene_product_level (SO:0002316) and increased_gene_product_level (SO:0002315)

### ISSUE THREAD

**Issue by davidwsant** [The-Sequence-Ontology/SO-Ontologies#612]
**What is the SO term name and accession?**
decreased_gene_product_level (SO:0002316)
increased_gene_product_level (SO:0002315)

**Describe what you would like to change.**
The Gene Curation Coalition (GenCC) has pointed out that there are variants that can change the stability of an RNA transcript rather than changing transcription levels. The definitions need to be updated to include these circumstances.

Here are proposed updates:
decreased_gene_product_level (SO:0002316): 
 - Original definition: A sequence variant that decreases the level of transcription of a gene. 
 - Proposed definition: A sequence variant that decreases the level of expression of a gene to any degree, including variants that entirely stop transcription expression. 
 
increased_gene_product_level (SO:0002315):
 - Original definition: A sequence variant that increases the level of transcription of a gene.
 - Proposed definition: A sequence variant that increases the level of expression of a gene.

**Comment by angharadroberts** [comment]
follwing Nicky's input here are proposed updates:

decreased_gene_product_level (SO:0002316):
    Original definition: A sequence variant that decreases the level of transcription of a gene.
    Proposed definition: a sequence variant that decreases the level or amount of gene product produced

increased_gene_product_level (SO:0002315):
    Original definition: A sequence variant that increases the level of transcription of a gene.
    Proposed definition: A variant that increases the level or amount of gene product produced

absent_gene_product  (SO:0002317):
   Original definition: a sequence variant that entirely stops the transcription of a gene
   Proposed definition: a sequence variant that results in no gene product

**Comment by angharadroberts** [comment]
also 

What is the SO term name and accession?
altered_gene_product_level  SO:0002314

Describe what you would like to change.
The Gene Curation Coalition (GenCC) has pointed out that there are variants that can change the stability of an RNA transcript rather than changing transcription levels. The definitions need to be updated to include these circumstances.

Here are proposed updates:
altered_gene_product_level  SO:0002314
Original definition:  A sequence variant that alters the level of transcription of a gene.
Proposed definition: A sequence variant that alters the level or amount of gene product produced. This high level term can be applied where the direction of level change (increased vs decreased gene product level) is unknown or not confirmed

**Comment by davidwsant** [comment]
Thank you for updating the definitions. The definitions have been updated and pushed to GitHub. Updates to the [SO Browser](http://www.sequenceontology.org/miso) should be visible within 24 hours.  

-Dave
