### ISSUE TITLE
NTR: range extender element

### ISSUE THREAD

**Issue by cmungall** [The-Sequence-Ontology/SO-Ontologies#649]
[Bower et al](https://doi.org/10.1101/2024.05.26.595809) describe a prototypical novel element that confers extreme-distance gene activation by remote enhancers.

name: range extender element
is_a: ??? DNA_motif? transcriptional_cis_regulatory_region?
synonym: REX
def: "A conserved cis-acting element that confers extreme-distance regulatory activity to an enhancer." [https://doi.org/10.1101/2024.05.26.595809]

**Comment by egchristensen** [comment]
What do you think of these edits @cmungall? 

---

**name:** range_extender_element
**is_a:** transcriptional_cis_regulatory_region
**synonym:** REX
**def:** A conserved cis-acting element that confers extreme-distance regulatory activity to an enhancer.  
**comment (to go under definition):** On its own, a range extender element is not a classical enhancer, but its addition can extend the range of action of a heterologous short-range enhancer by more than 10-fold compared to its native range. In extreme cases, extended ranges may span approximately 840 kilobases of genomic space. The evolutionarily conserved homeodomain motif [C/T]AATA, required for long-range enhancer activity, is present within the range extender element. Range extender elements are distinct from and do not share sequence similarity with other cis-regulatory elements like tethering and remote control elements in Drosophila; or CTCF sites, CpG islands, and enhancer booster elements in mammals. Rather than conferring robustness of remote enhancer activity, a range extender element is both required and sufficient for long-range enhancer-promoter activation.
**database_cross_reference (to go under definition):** [https://doi.org/10.1101/2024.05.26.595809]
**comment:** Added at the request of Chris Mungall (Berkeley Lab). See GitHub Issue #649. 

---

Some notes:

It appears that range extender elements contain a "DNA_motif" with sequence [C/T]AATA but Bower et al don't seem to define range extender elements just with that motif. They focus a lot on the effect it has on the action of classical enhancers so I think transcriptional_cis_regulatory_region is a good parent term. 

Do we also want to include the parts of this entity in SO? 

- Bower et al. refer to the region contained with a range extender element as "[C/T]AATA homeodomain motifs". It seems like a better label for that motif would be something along the lines of "[C/T]AATA_homeobox_motif" since homeodomains are found on amino acid sequence and not DNA sequence. "[C/T]AATA_homeobox_motif" could then be related with "range_extender_element" via a "part_of" or "contained_by" relationship.

- If we add "[C/T]AATA_homeobox_motif" (or something similar) then we may want to also add a term for "homeobox" under transcriptional_cis_regulatory_region.

Also, does the definition of this feature need to be restricted to the development of certain anatomical features to reflect the work cited?

**Comment by cmungall** [comment]
great!

**Comment by egchristensen** [comment]
Created a new term for range_extender_element with accession SO:0002382. Changes should be reflected on sequenceontology.org within 24 hours.
